// Explicit operator-only cloud integration verification. Does not create accounts
// or call providers. It creates one fictional private memory, then archives it.
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { createClient } from '@supabase/supabase-js';
let stage='configuration',token='',memoryId='';const stages=[];
function need(name){const value=process.env[name];if(!value)throw Error('CONFIGURATION_REQUIRED');return value;}
const base=process.env.PUBLIC_APP_URL||'';
function expect(value){if(!value)throw Error('ASSERTION_FAILED');}
async function call(action,body,session='',headers={},method,query={}){
 const url=new URL('/api/giftportals',base);url.search=new URLSearchParams({action,...query}).toString();
 const response=await fetch(url,{method:method||(body===undefined?'GET':'POST'),headers:{'Content-Type':'application/json',...(session?{Authorization:`Bearer ${session}`} : {}),...headers},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(15000),redirect:'error'});
 let result;try{result=await response.json();}catch{throw Error('API_RESPONSE_INVALID');}return{...result,status:response.status};
}
function success(result){expect(result.ok&&result.status===200);return result.data;}
function pass(name){stages.push(name);}
async function main(){
 if(process.env.RUN_CLOUD_INTEGRATION!=='true')throw Error('EXPLICIT_OPERATOR_FLAG_REQUIRED');expect(base.startsWith('https://')&&!base.includes('.invalid'));
 stage='cloud-status';const state=success(await call('status'));expect(state.configured===true&&state.generationEnabled===false);pass(stage);
 stage='private-auth';const owner=success(await call('login',{email:need('QA_OWNER_EMAIL'),password:need('QA_OWNER_PASSWORD')})),recipient=success(await call('login',{email:need('QA_RECIPIENT_EMAIL'),password:need('QA_RECIPIENT_PASSWORD')}));expect(!owner.user.demo&&!recipient.user.demo&&owner.user.id!==recipient.user.id);token=owner.accessToken;pass(stage);
 stage='create-private-memory';const original={title:'Fictional cloud verification postcard',story:'Synthetic integration-test story. No real travel, personal photo, or gift is represented.',location:{placeId:'tuca',label:'Fictional TUCA test',latitude:-23.538868,longitude:-46.671081,source:'manual',experiencedAt:new Date().toISOString().slice(0,10)},aiConsent:false,shareLocation:false};const memory=success(await call('memory',original,token));memoryId=memory.id;expect(memory.location.placeId==='tuca'&&memory.shareLocation===false);pass(stage);
 stage='original-consent';const bytes=await readFile(fileURLToPath(new URL('../public/demo/perdizes-input.png',import.meta.url)));const denied=await call('upload',{memoryId,kind:'gift-photo',mimeType:'image/png',bytes:bytes.length,consent:true,metadataConsent:false},token);expect(!denied.ok&&denied.error.code==='MEDIA_CONSENT_REQUIRED');pass(stage);
 stage='original-upload';const upload=success(await call('upload',{memoryId,kind:'gift-photo',mimeType:'image/png',bytes:bytes.length,consent:true,metadataConsent:true},token));const saved=await fetch(upload.signedUploadUrl,{method:'PUT',headers:{'Content-Type':'image/png','x-upsert':'false'},body:bytes,signal:AbortSignal.timeout(20000),redirect:'error'});expect(saved.ok);const completed=success(await call('media-complete',{mediaId:upload.mediaId},token));expect(completed.media.some(x=>x.id===upload.mediaId&&x.bytes===bytes.length));pass(stage);
 stage='persistence-readback';let ownerWorld=success(await call('world',undefined,token));expect(ownerWorld.memories.some(m=>m.id===memoryId&&m.media.some(x=>x.id===upload.mediaId)));let recipientWorld=success(await call('world',undefined,recipient.accessToken));expect(!recipientWorld.memories.some(m=>m.id===memoryId));pass(stage);
 stage='read-only-link';const readGift=success(await call('share',{memoryId,message:'Synthetic read-only link',allowLinkRead:true,allowClaim:false},token));expect(!readGift.claimToken);const read=success(await call('gift',undefined,'',{'X-Gift-Token':readGift.token}));expect(read.memory.id===memoryId&&read.memory.location.placeId==='world'&&read.canClaim===false);const noClaim=await call('claim',{token:readGift.token},recipient.accessToken);expect(!noClaim.ok&&noClaim.error.code==='CLAIM_PERMISSION_REQUIRED');pass(stage);
 stage='claim-invitation';const gift=success(await call('share',{memoryId,message:'Synthetic transferable claim invitation',allowLinkRead:true,allowClaim:true},token));expect(gift.claimToken&&gift.claimToken!==gift.token);const view=success(await call('gift',undefined,'',{'X-Gift-Token':gift.token,'X-Gift-Claim':gift.claimToken}));expect(view.canClaim===true);success(await call('claim',{token:gift.token,claimToken:gift.claimToken},recipient.accessToken));recipientWorld=success(await call('world',undefined,recipient.accessToken));expect(recipientWorld.memories.some(m=>m.id===memoryId&&m.location.placeId==='world'));expect(!recipientWorld.discoveries.some(d=>d.memoryId===memoryId));pass(stage);
 stage='recipient-owner-denial';const notOwner=await call('memory',undefined,recipient.accessToken,{},'DELETE',{id:memoryId});expect(!notOwner.ok&&notOwner.status>=400&&notOwner.status<500);pass(stage);
 stage='browser-write-denial';const direct=createClient(need('SUPABASE_URL'),need('SUPABASE_ANON_KEY'),{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:`Bearer ${token}`},fetch:(url,init)=>fetch(url,{...init,signal:AbortSignal.timeout(15000)})}});const write=await direct.from('gp_memories').update({title:'Forbidden direct write'}).eq('id',memoryId);expect(Boolean(write.error));pass(stage);
 stage='location-edit-recalculation';success(await call('memory',{...original,memoryId,shareLocation:true},token,{},'PATCH'));recipientWorld=success(await call('world',undefined,recipient.accessToken));expect(recipientWorld.discoveries.some(d=>d.memoryId===memoryId&&d.kind==='memory'&&d.placeId==='tuca'));expect(!recipientWorld.discoveries.some(d=>d.memoryId===memoryId&&d.kind==='physical'));pass(stage);
 stage='revoke-readback';success(await call('revoke',{giftId:gift.id},token));const revoked=await call('gift',undefined,'',{'X-Gift-Token':gift.token});expect(!revoked.ok);recipientWorld=success(await call('world',undefined,recipient.accessToken));expect(!recipientWorld.memories.some(m=>m.id===memoryId)&&!recipientWorld.discoveries.some(d=>d.memoryId===memoryId));pass(stage);
 stage='physical-history-independent';const visit=success(await call('discovery',{placeId:'tuca',kind:'physical',memoryId},token));success(await call('memory',undefined,token,{},'DELETE',{id:memoryId}));ownerWorld=success(await call('world',undefined,token));expect(!ownerWorld.memories.some(m=>m.id===memoryId)&&ownerWorld.discoveries.some(d=>d.id===visit.id&&d.kind==='physical'));const archive=success(await call('world',undefined,token,{},undefined,{archived:'true'}));expect(archive.memories.some(m=>m.id===memoryId&&m.archivedAt));pass(stage);
 stage='restore-without-reviving-links';success(await call('restore',{memoryId},token));expect(!(await call('gift',undefined,'',{'X-Gift-Token':gift.token})).ok);pass(stage);
 stage='paused-generation';const paused=await call('generate',{memoryId,provider:'tripo',dedupeKey:'cloud-verification-no-spend'},token);expect(!paused.ok&&paused.error.code==='GENERATION_PAUSED');const retry=await call('retry',{jobId:'00000000-0000-4000-a000-000000000000'},token);expect(!retry.ok&&retry.error.code==='GENERATION_PAUSED');pass(stage);
 stage='archive-test-fixture';success(await call('memory',undefined,token,{},'DELETE',{id:memoryId}));success(await call('discovery',undefined,token,{},'DELETE',{id:visit.id}));pass(stage);
 process.stdout.write(JSON.stringify({ok:true,label:'Actual cloud private-route readbacks; fictional inputs',generationMustRemainPaused:true,passedStages:stages.length,stages,finishedAt:new Date().toISOString()})+'\n');
}
main().catch(async()=>{if(token&&memoryId)try{await call('memory',undefined,token,{},'DELETE',{id:memoryId});}catch{}process.stderr.write(JSON.stringify({ok:false,error:{code:'CLOUD_VERIFICATION_FAILED',stage},passedStages:stages,generationMustRemainPaused:true})+'\n');process.exitCode=1;});
