import assert from 'node:assert/strict';
import test from 'node:test';
import { resolve } from 'node:path';
import { gzipSync } from 'node:zlib';
import { createTSLoader,here } from './cloud-instant-test-loader.mjs';
const stub=`export const cloudInstantConfigured=()=>false;export const createCloudInstantRepository=()=>({});export const createCloudProviderAdapter=()=>({});export const createRemoteCloudModerator=()=>({configured:false});`;
const load=createTSLoader(new Map([[resolve(here,'_lib/cloud-instant-adapters.ts'),stub]]));
const {createCloudInstantHandler}=await load(resolve(here,'instant-cloud.ts'));
const {createCloudTickHandler}=await load(resolve(here,'instant-cloud-tick.ts'));
const {createCloudProviderHTTP,cloudRemaining}=await load(resolve(here,'_lib/cloud-instant-provider-http.ts'));
process.env.GIFTPORTALS_CLOUD_ORIGIN='https://gift.example';process.env.CLOUD_DEDUPE_SECRET='offline-unit-test-secret-32characters-min';process.env.CRON_SECRET='offline-cron-secret';process.env.TRIPO_API_KEY='offline-provider-key';process.env.WORLD_LABS_API_KEY='offline-world-key';
const response=()=>({headers:{},statusCode:0,setHeader(name,value){this.headers[name]=value;},end(body){this.body=JSON.parse(body);}});
const request=(action,extra={})=>({method:'POST',url:`/api/instant-cloud?action=${action}`,headers:{host:'gift.example',origin:'https://gift.example','sec-fetch-site':'same-origin','content-type':'application/json','x-instant-token':'A'.repeat(43)},body:{id:'00000000-0000-4000-8000-000000000000'},...extra});
function app(){const calls=[];const service=Object.fromEntries(['status','prepare','finalize','get','advance','tick'].map(method=>[method,async(...values)=>{calls.push([method,...values]);return{method};}]));return{calls,handler:createCloudInstantHandler(service),worker:createCloudTickHandler(service)};}
const reject=(promise,code)=>assert.rejects(promise,error=>error.code===code);

test('public GET status and capability GET job cannot call workers, uploads or submissions',async()=>{const f=app();for(const action of['status','job']){const res=response();await f.handler(request(action,{method:'GET',body:undefined}),res);assert.equal(res.statusCode,200);assert.equal(res.body.ok,true);assert.equal(res.headers['Cache-Control'],'no-store');assert.equal(res.headers['Referrer-Policy'],'no-referrer');}assert.deepEqual(f.calls.map(([kind])=>kind),['status','get']);});
test('capability advance is POST only, same origin and forwards exact id and token',async()=>{const f=app(),res=response();await f.handler(request('advance'),res);assert.equal(res.statusCode,200);assert.deepEqual(f.calls[0],['advance','00000000-0000-4000-8000-000000000000','A'.repeat(43)]);const denied=response();await f.handler(request('advance',{method:'GET'}),denied);assert.equal(denied.statusCode,405);assert.equal(f.calls.length,1);});
test('writes reject crosssite/missing/wrong origins and foreign hosts before service calls',async()=>{for(const headers of[{host:'gift.example','content-type':'application/json'},{host:'gift.example',origin:'https://evil.example','content-type':'application/json'},{host:'evil.example',origin:'https://gift.example','content-type':'application/json'},{host:'gift.example',origin:'https://gift.example','sec-fetch-site':'cross-site','content-type':'application/json'}]){const f=app(),res=response();await f.handler(request('prepare',{headers}),res);assert.equal(res.statusCode,403);assert.equal(res.body.error.code,'ORIGIN_DENIED');assert.equal(f.calls.length,0);}});
test('small declaration body bound rejects oversized JSON, arrays, malformed JSON and binary MIME',async()=>{for(const extra of[{body:{id:'x'.repeat(17000)}},{body:[]},{body:'{'},{headers:{host:'gift.example',origin:'https://gift.example','content-type':'image/png'},body:'data:image/png;base64,AAAA'}]){const f=app(),res=response();await f.handler(request('prepare',extra),res);assert.equal(res.body.ok,false);assert.equal(f.calls.length,0);}const f=app(),res=response();await f.handler(request('prepare',{body:{id:'x'.repeat(17000)}}),res);assert.equal(res.statusCode,413);});
test('no-login prepare assigns a secure signed owner cookie while capabilities remain explicit',async()=>{const f=app(),res=response();await f.handler(request('prepare'),res);assert.equal(res.statusCode,200);assert.match(res.headers['Set-Cookie'],/^__Host-gp_instant_owner=[A-Za-z0-9_-]{43}\.[A-Za-z0-9_-]{43}; Path=\/; Secure; HttpOnly; SameSite=Strict;/);assert.match(f.calls[0][2],/^[a-f0-9]{64}$/);assert.equal(res.body.data.method,'prepare');});
test('authenticated cron GET/POST is the only global worker authority and invalid secret never claims',async()=>{for(const method of['GET','POST']){const f=app(),res=response();await f.worker({method,headers:{authorization:'Bearer offline-cron-secret'}},res);assert.equal(res.statusCode,200);assert.equal(f.calls[0][0],'tick');}const f=app(),res=response();await f.worker({method:'GET',headers:{authorization:'Bearer wrong'}},res);assert.equal(res.statusCode,403);assert.equal(f.calls.length,0);assert.equal(res.body.error.code,'TICK_FORBIDDEN');});
test('provider deadline uses remaining invocation time and fails closed before expired requests',async()=>{assert.equal(cloudRemaining(Date.now()+200000,120000,20000),120000);assert.ok(cloudRemaining(Date.now()+30000,120000,20000)<=10000);assert.throws(()=>cloudRemaining(Date.now()-1,15000),error=>error.code==='CLOUD_TIME_SLICE_ENDED');let fetched=false;const savedFetch=globalThis.fetch;globalThis.fetch=async()=>{fetched=true;throw new Error('must not run');};try{await reject(createCloudProviderHTTP(Date.now()+1000).json('tripo','/generation/image-to-model','POST',{}),'CLOUD_TIME_SLICE_ENDED');assert.equal(fetched,false);}finally{globalThis.fetch=savedFetch;}});
test('paid POST lost response is ambiguous while known GET failure remains retryable',async()=>{const savedFetch=globalThis.fetch;globalThis.fetch=async()=>{throw new Error('offline disconnect');};try{const http=createCloudProviderHTTP(Date.now()+165000);await reject(http.json('tripo','/generation/image-to-model','POST',{}),'SUBMISSION_AMBIGUOUS');await reject(http.json('tripo','/tasks/known-id'),'PROVIDER_NETWORK');await reject(http.json('worldlabs','/media-assets:prepare_upload','POST',{}),'PROVIDER_NETWORK');}finally{globalThis.fetch=savedFetch;}});
test('paid rejection logs only enum and numeric metadata while preserving ambiguity and never retrying',async()=>{const savedFetch=globalThis.fetch,savedError=console.error,logs=[];let calls=0;console.error=value=>logs.push(JSON.parse(value));try{globalThis.fetch=async()=>{calls++;return new Response(JSON.stringify({code:1001,message:'private input token secret https://storage.invalid/?token=private',details:{prompt:'private story'}}),{status:400,headers:{'x-tripo-trace-id':'00000000-0000-4000-8000-000000000000'}});};await reject(createCloudProviderHTTP(Date.now()+165000).json('tripo','/generation/image-to-image','POST',{input:'private-file-token',prompt:'private story'}),'PROVIDER_REQUEST_REJECTED');assert.equal(calls,1);assert.equal(logs.length,1);assert.deepEqual({...logs[0],durationMs:0},{event:'cloud_provider_submission_error',provider:'tripo',stage:'tripo-reference',httpStatus:400,providerCode:1001,errorCode:'PROVIDER_REQUEST_REJECTED',durationMs:0,traceId:'00000000-0000-4000-8000-000000000000'});assert.doesNotMatch(JSON.stringify(logs),/private|storage\.invalid|prompt|input|Authorization/);logs.length=0;globalThis.fetch=async()=>new Response(JSON.stringify({code:'private-token',message:'secret'}),{status:403,headers:{'x-tripo-trace-id':'private-token'}});await reject(createCloudProviderHTTP(Date.now()+165000).json('tripo','/generation/image-to-image','POST',{}),'PROVIDER_REQUEST_REJECTED');assert.equal(logs[0].providerCode,null);assert.equal(logs[0].traceId,null);}finally{globalThis.fetch=savedFetch;console.error=savedError;}});
test('provider responses reject oversized JSON, invalid envelopes and failed known tasks without accepting a fabricated ID',async()=>{const savedFetch=globalThis.fetch;try{for(const body of['x'.repeat(1024*1024+1),'{','[]',JSON.stringify({code:0,data:[]})]){globalThis.fetch=async()=>new Response(body);await assert.rejects(createCloudProviderHTTP(Date.now()+165000).json('tripo','/tasks/known-id'));}await reject(createCloudProviderHTTP(Date.now()+165000).complete('tripo',{status:'failed'}),'PROVIDER_GENERATION_FAILED');}finally{globalThis.fetch=savedFetch;}});
test('generated asset URLs require approved HTTPS hosts before any download',async()=>{const savedFetch=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;throw new Error('must not run');};try{for(const url of['http://assets.tripo3d.ai/model.glb','https://tripo3d.ai.evil.example/model.glb','https://user:pass@assets.tripo3d.ai/model.glb','https://127.0.0.1/model.glb'])await reject(createCloudProviderHTTP(Date.now()+165000).complete('tripo',{status:'success',output:{model_url:url}}),'PROVIDER_ASSET_ORIGIN_DENIED');assert.equal(calls,0);}finally{globalThis.fetch=savedFetch;}});
test('actual GLB/SPZ headers, decompressed splat limits and numerical semantics are verified',async()=>{const savedFetch=globalThis.fetch;const glb=Buffer.alloc(12);glb.write('glTF');glb.writeUInt32LE(2,4);glb.writeUInt32LE(12,8);const png=Buffer.from([137,80,78,71,13,10,26,10,1]);const decoded=Buffer.alloc(16);decoded.write('NGSP');decoded.writeUInt32LE(500000,8);const spz=gzipSync(decoded);const world={world_id:'world-1',assets:{splats:{spz_urls:{'500k':'https://assets.worldlabs.ai/world.spz'},semantics_metadata:{metric_scale_factor:2.9049978,ground_plane_offset:1.6893421,private:'not exported'}},imagery:{pano_url:'https://assets.worldlabs.ai/pano.png'},mesh:{collider_mesh_url:'https://assets.worldlabs.ai/collider.glb'}}};try{globalThis.fetch=async url=>new Response(String(url).endsWith('.spz')?spz:String(url).endsWith('.png')?png:glb);const complete=await createCloudProviderHTTP(Date.now()+165000).complete('worldlabs',{done:true,response:world});assert.deepEqual(complete.worldSemantics,{metricScaleFactor:2.9049978,groundPlaneOffset:1.6893421});assert.equal(complete.worldQuality,'500k');assert.equal(complete.colliderStatus,'available');assert.deepEqual(complete.assets.map(a=>a.key),['generated-world','panorama','collider']);decoded.writeUInt32LE(600001,8);globalThis.fetch=async()=>new Response(gzipSync(decoded));await reject(createCloudProviderHTTP(Date.now()+165000).complete('worldlabs',{done:true,response:world}),'PROVIDER_ASSET_INVALID');globalThis.fetch=async()=>new Response('not a GLB');await reject(createCloudProviderHTTP(Date.now()+165000).complete('tripo',{status:'success',output:{model_url:'https://assets.tripo3d.ai/model.glb'}}),'PROVIDER_ASSET_INVALID');}finally{globalThis.fetch=savedFetch;}});
