import assert from 'node:assert/strict';
import test from 'node:test';
import { resolve } from 'node:path';
import { createTSLoader,here } from './cloud-instant-test-loader.mjs';
const {collectCloudExpired}=await createTSLoader()(resolve(here,'_lib/cloud-instant-retention.ts'));
const id='00000000-0000-4000-8000-000000000000',sha='a'.repeat(64);
function repo(extra={}){const calls=[],files=new Map([['gp-instant-private',[{name:`original-${sha}.png`}]],['gp-instant-generated',[{name:`${sha}.spz`},{name:`${sha}.glb`}]]]);return{calls,files,async expired(){return[{id,prefix:`${id}/`}];},async list(bucket,prefix){calls.push(['list',bucket,prefix]);return files.get(bucket);},async remove(bucket,paths){calls.push(['remove',bucket,paths]);files.set(bucket,[]);},async purge(value){calls.push(['purge',value]);},...extra};}
test('retention deletes only exact scoped filenames in both private buckets before releasing storage',async()=>{const f=repo(),result=await collectCloudExpired(f);assert.deepEqual(result,{processed:1,purged:1});assert.deepEqual(f.calls.filter(([kind])=>kind==='remove').map(([,bucket,paths])=>[bucket,paths]),[['gp-instant-private',[`${id}/input/original-${sha}.png`]],['gp-instant-generated',[`${id}/generated/${sha}.spz`,`${id}/generated/${sha}.glb`]]]);assert.equal(f.calls.at(-1)[0],'purge');});
test('retention leaves storage reserved if either bucket deletion is incomplete or unavailable',async()=>{for(const failure of['incomplete','failed']){const f=repo({async remove(){if(failure==='failed')throw new Error('offline storage');}});await assert.rejects(collectCloudExpired(f));assert.equal(f.calls.some(([kind])=>kind==='purge'),false);}});
test('malformed UUID, parent prefix or traversal filename cannot delete any object or purge another gift',async()=>{for(const extra of[{async expired(){return[{id:'../escape',prefix:'../escape/'}];}},{async expired(){return[{id,prefix:'/'}];}},{async list(){return[{name:'../../someone-else/photo.png'}];}},{async list(){return[{name:'nested-directory'}];}}]){const f=repo(extra);await assert.rejects(collectCloudExpired(f));assert.equal(f.calls.some(([kind])=>kind==='remove'||kind==='purge'),false);}});
test('retention batch is finite and empty prefixes can safely retry without a second delete',async()=>{const f=repo();await collectCloudExpired(f);const deletes=f.calls.filter(([kind])=>kind==='remove').length;await collectCloudExpired(f);assert.equal(f.calls.filter(([kind])=>kind==='remove').length,deletes);for(const limit of[0,5,1000,NaN])await assert.rejects(collectCloudExpired(f,limit));});
