import assert from 'node:assert/strict';
import test from 'node:test';
import { createHash } from 'node:crypto';
import { resolve } from 'node:path';
import { createTSLoader,here } from './cloud-instant-test-loader.mjs';
const load=createTSLoader();
const {createCloudInstantService,cloudInputDocument,verifyCloudSafety,cloudRequestHash}=await load(resolve(here,'_lib/cloud-instant-service.ts'));
const {AppError,giftHash}=await load(resolve(here,'_lib/rules.ts'));
const hash=bytes=>createHash('sha256').update(bytes).digest('hex'),copy=structuredClone;
const token='A'.repeat(43),otherToken='B'.repeat(43),secret='test-only-secret-for-offline-tests-123456789';
const png=Buffer.from([137,80,78,71,13,10,26,10,7,1,2,3]),png2=Buffer.from([137,80,78,71,13,10,26,10,9,4,5,6]);
const image=bytes=>({mime:'image/png',bytes:bytes.length,sha256:hash(bytes)});
const input=extra=>({title:'A real memory',worldPrompt:'A calm remembered plaza',story:'My exact story',dedication:'For you',senderName:'Alice',recipientName:'Bob',photoIntent:'object',requestToken:token,dedupeKey:'stable-request-01',consent:true,images:{original:image(png)},...extra});
const report=(images,decision='allow')=>({protocol:'giftportals-cloud-vision-v1',modelVersion:'offline-vision-v1',checkedAt:'2026-10-04T00:00:00.000Z',decision,results:images.map(image=>({id:image.id,sha256:image.sha256,modelVersion:'offline-vision-v1',decision,category:decision==='allow'?'ordinary':decision==='block'?'sexual':'uncertain'}))});
function fixture(options={}){
  const jobs=new Map(),requests=new Map(),bytes=new Map(),journal=[];let leases=0;
  const checked=(id,cap)=>{const job=jobs.get(id);if(!job||job.tokenHash!==cap)throw new AppError('JOB_UNAVAILABLE',404);return job;};
  const cas=job=>{const old=jobs.get(job.id);if(!old||old.lease_id!==job.lease_id||!old.lease_id||old.revision!==job.revision)throw new AppError('INSTANT_LEASE_CONFLICT',409);return old;};
  const publicJob=job=>{const{tokenHash,requestKeyHash,inputHash,ownerHash,...value}=job;return copy(value);};
  const repository={
    async prepare(v){journal.push(['prepare']);const old=requests.get(v.requestKeyHash);if(old){const job=jobs.get(old);if(job.tokenHash!==v.tokenHash||job.inputHash!==v.inputHash||job.ownerHash!==v.ownerHash)throw new AppError('DEDUPE_MISMATCH',409);return{job:publicJob(job),deduplicated:true};}const job={...v,state:'awaiting_upload',document:copy(v.document),stages:{},assets:{},revision:0,created_at:'2026-10-04T00:00:00Z',updated_at:'2026-10-04T00:00:00Z',lease_id:null};jobs.set(v.id,job);requests.set(v.requestKeyHash,v.id);return{job:publicJob(job),deduplicated:false};},
    async get(id,cap){journal.push(['get',id]);return publicJob(checked(id,cap));},
    async lookup(key,cap){return publicJob(checked(requests.get(key),cap));},
    async finalize(id,cap,assets){const job=checked(id,cap);if(job.state==='awaiting_upload'){job.assets=copy(assets);job.state='queued';job.revision++;}return publicJob(job);},
    async claim(worker,id){journal.push(['claim',id]);const job=[...jobs.values()].find(job=>(!id||job.id===id)&&!job.lease_id&&(['queued','processing'].includes(job.state)||(job.state==='submission_uncertain'&&Object.values(job.stages).some(stage=>stage.state==='processing'&&stage.taskId))));if(!job)return null;job.state=job.state==='submission_uncertain'?job.state:'processing';job.lease_id=`lease-${++leases}`;job.revision++;return publicJob(job);},
    async begin(value,stage){const job=cas(value);assert.equal(job.state,'processing');assert.equal(job.stages[stage],undefined);assert.equal(job.document.stageFailures?.[stage],undefined);assert.equal(job.document.photoSafety?.decision,'allow');job.stages[stage]={state:'submitting',progress:0,submittedAt:'2026-10-04T00:00:01Z'};job.revision++;journal.push(['begin',stage]);return publicJob(job);},
    async update(value,changes){const job=cas(value);job.state=changes.state;job.document=copy(changes.document);job.stages=copy(changes.stages);job.assets=copy(changes.assets);job.revision++;if(changes.releaseLease!==false)job.lease_id=null;journal.push(['update',job.state]);return publicJob(job);},
    async signUpload(asset){return`https://storage.invalid/upload/${asset.path}`;},
    async signRead(asset){journal.push(['signRead',asset.id]);return`https://storage.invalid/read/${asset.path}`;},
    async download(asset){journal.push(['download',asset.id]);if(!bytes.has(asset.path))throw new AppError('IMAGE_CONTENT_INVALID');return Buffer.from(bytes.get(asset.path));},
    async upload(asset,value){journal.push(['store',asset.id]);const old=bytes.get(asset.path);if(old)assert.equal(hash(old),hash(value));bytes.set(asset.path,Buffer.from(value));},
    async status(){return{canCreate:options.canCreate!==false,budget:{tripo:{cap:1000},worldlabs:{cap:20000}}};},
  };
  const generated=(key,value,suffix='png',mime='image/png')=>({key,bytes:value,suffix,mime,sha256:hash(value)});
  const providers={
    async credit(provider,reservation){journal.push(['credit',provider,reservation]);},
    async upload(provider,value,mime){journal.push(['providerUpload',provider,hash(value),mime]);return`uploaded-${provider}`;},
    async submit(stage,job){journal.push(['submit',stage]);assert.equal(jobs.get(job.id).stages[stage].state,'submitting','Durable intent precedes paid submit');if(options.submitError)throw options.submitError;return`task-${stage}`;},
    async poll(stage,id){journal.push(['poll',stage,id]);if(options.pollError)throw options.pollError;return{progress:100};},
    async complete(stage){if(options.incomplete)return null;return stage==='tripo-reference'?{assets:[generated('reference',png2)]}:stage==='tripo'?{assets:[generated('model',Buffer.from('model'),'glb','model/gltf-binary')]}:{assets:[generated('generated-world',Buffer.from('spz'),'spz','application/octet-stream'),generated('panorama',png2),generated('collider',Buffer.from('collider'),'glb','model/gltf-binary')],worldSemantics:options.semantics||{metricScaleFactor:2.9049978,groundPlaneOffset:1.6893421},worldQuality:'500k',colliderStatus:'available'};},
  };
  const moderator={configured:options.moderatorConfigured!==false,async screen(images){journal.push(['moderate',images.map(image=>image.id)]);return options.moderationReport?options.moderationReport(images):report(images,options.decision||'allow');}};
  const service=()=>createCloudInstantService({repository,providers,moderator,settings:()=>({enabled:options.enabled!==false,providers:{tripo:true,worldlabs:true},dedupeSecret:secret})});
  async function prepared(value=input()){const out=await service().prepare(value,'c'.repeat(64));for(const upload of out.uploads)bytes.set(upload.url.replace('https://storage.invalid/upload/',''),Buffer.from(upload.id==='original'?png:png2));return out;}
  async function queued(value=input()){const out=await prepared(value);await service().finalize(out.id,out.token);return out;}
  return{service,repository,providers,moderator,jobs,bytes,journal,prepared,queued};
}
const rejectCode=(promise,code)=>assert.rejects(promise,error=>error.code===code);

test('prepare deduplicates the exact immutable recipe without provider calls and rejects changed input',async()=>{const f=fixture(),source=input(),snapshot=copy(source),first=await f.prepared(source),second=await f.service().prepare(source,'c'.repeat(64));assert.equal(first.id,second.id);assert.equal(second.deduplicated,true);assert.equal(f.jobs.size,1);assert.deepEqual(source,snapshot);assert.equal(f.journal.some(([kind])=>['submit','providerUpload','credit','moderate'].includes(kind)),false);await rejectCode(f.service().prepare(input({story:'changed'}),'c'.repeat(64)),'DEDUPE_MISMATCH');assert.equal(cloudRequestHash(token,'stable-request-01',secret),cloudRequestHash(token,'stable-request-01',secret));assert.notEqual(cloudRequestHash(token,'stable-request-01',secret),cloudRequestHash(otherToken,'stable-request-01',secret));});
test('metadata enforces consent, image limits, hashes, roles, prompt lengths, explicit recipe and exact story',()=>{const doc=cloudInputDocument(input({photoIntent:'place'}));assert.equal(doc.needsReference,true);assert.equal(doc.generation.tripo.face_limit,30000);assert.equal(doc.generation.worldlabs.model,'marble-1.1');assert.equal(doc.generation.tripoReference.model,'chat_image_2');assert.equal(doc.story,'My exact story');for(const bad of[{consent:false},{photoIntent:'other'},{images:{original:{...image(png),bytes:6*1024*1024+1}}},{images:{original:{...image(png),sha256:'no'}}},{images:{original:null}},{images:{original:image(png),audio:image(png)}},{worldPrompt:'short'},{photoIntent:'place',images:{original:image(png),object:image(png2)}},{photoIntent:'place',objectImageRole:'miniature-reference',images:{original:image(png),object:image(png)}}])assert.throws(()=>cloudInputDocument(input(bad)),error=>Boolean(error.code));});
test('finalize verifies original plus every derivative against actual bytes and leaves all bytes private before moderation',async()=>{const f=fixture(),out=await f.prepared(input({images:{original:image(png),object:image(png2),world:image(png2)}})),job=f.jobs.get(out.id);const badPath=out.uploads.find(v=>v.id==='world').url.replace('https://storage.invalid/upload/','');f.bytes.set(badPath,png);await rejectCode(f.service().finalize(out.id,token),'IMAGE_CONTENT_INVALID');assert.equal(job.state,'awaiting_upload');f.bytes.set(badPath,png2);const dto=await f.service().finalize(out.id,token);assert.equal(dto.state,'processing');assert.equal(dto.assets.photoUrl,'');assert.equal(f.journal.some(([kind])=>kind==='signRead'||kind==='submit'),false);});
test('capability cannot read or advance another gift; advance leases only its validated gift',async()=>{const f=fixture(),first=await f.queued(),second=await f.queued(input({requestToken:otherToken,dedupeKey:'second-request-01'}));await rejectCode(f.service().advance(second.id,token),'JOB_UNAVAILABLE');assert.equal(f.journal.filter(([kind])=>kind==='claim').length,0);await f.service().advance(first.id,token);assert.deepEqual(f.journal.filter(([kind])=>kind==='claim').map(([,id])=>id),[first.id]);assert.equal(f.jobs.get(second.id).document.photoSafety,undefined);await rejectCode(f.service().get({id:first.id,token:otherToken}),'JOB_UNAVAILABLE');});
test('all-input moderation blocks or holds review before any provider upload or paid submit',async()=>{for(const decision of['block','review']){const f=fixture({decision}),out=await f.queued(input({images:{original:image(png),object:image(png2),world:image(png2)}}));await f.service().tick('worker');assert.deepEqual(f.journal.find(([kind])=>kind==='moderate')[1],['original','object','world']);assert.equal(f.jobs.get(out.id).state,'failed');assert.equal(f.journal.some(([kind])=>['providerUpload','submit','credit','signRead'].includes(kind)),false);assert.equal((await f.service().get({id:out.id,token})).assets.photoUrl,'');}});
test('moderation proofs require every exact hash and the same named model; malformed proof cannot authorize paid calls',async()=>{const images=[{id:'original',sha256:hash(png),mime:'image/png',bytes:png}];for(const bad of[{...report(images),protocol:'other'},{...report(images),modelVersion:''},{...report(images),results:[]},{...report(images),results:[{...report(images).results[0],sha256:hash(png2)}]},{...report(images),results:[{...report(images).results[0],modelVersion:'other'}]}])assert.throws(()=>verifyCloudSafety(bad,images),error=>error.code==='PHOTO_SAFETY_UNAVAILABLE');const f=fixture({moderationReport:images=>({...report(images),results:[]})}),out=await f.queued();await f.service().tick('worker');assert.equal(f.journal.some(([kind])=>kind==='submit'),false);assert.equal(f.jobs.get(out.id).document.photoSafety,undefined);});
test('full object flow survives a fresh service for every tick, submits each provider once and keeps inputworld separate from generatedworld',async()=>{const f=fixture(),out=await f.queued(input({images:{original:image(png),world:image(png2)}}));for(let i=0;i<6;i++)await f.service().tick(`worker-${i}`);const dto=await f.service().get({id:out.id,token});assert.equal(dto.state,'completed');assert.equal(dto.story,'My exact story');assert.deepEqual(f.journal.filter(([kind])=>kind==='submit').map(([,stage])=>stage),['worldlabs','tripo']);assert.deepEqual(f.journal.filter(([kind])=>kind==='poll').map(([,stage,id])=>[stage,id]),[['tripo','task-tripo'],['worldlabs','task-worldlabs']]);assert.match(dto.assets.worldUrl,/generated\//);assert.match(f.jobs.get(out.id).assets.world.path,/input\/world-/);assert.notEqual(f.jobs.get(out.id).assets.world.path,f.jobs.get(out.id).assets['generated-world'].path);assert.deepEqual(dto.generation.worldlabs.worldSemantics,{metricScaleFactor:2.9049978,groundPlaneOffset:1.6893421});assert.equal('lease_id'in dto,false);assert.equal('document'in dto,false);assert.equal('expires_at'in dto,false);const before=f.journal.length;await f.service().get({id:out.id,token});assert.equal(f.journal.slice(before).some(([kind])=>['submit','poll','claim'].includes(kind)),false);});
test('place flow separately moderates its generated miniature before the model POST',async()=>{const f=fixture(),out=await f.queued(input({photoIntent:'place'}));for(let i=0;i<9;i++)await f.service().tick(`worker-${i}`);const submissions=f.journal.filter(([kind])=>kind==='submit').map(([,stage])=>stage);assert.deepEqual(submissions,['tripo-reference','worldlabs','tripo']);const derived=f.journal.findIndex(([kind,ids])=>kind==='moderate'&&ids.length===1&&ids[0]==='object'),model=f.journal.findIndex(([kind,stage])=>kind==='submit'&&stage==='tripo');assert.ok(derived>=0&&derived<model);assert.equal((await f.service().get({id:out.id,token})).state,'completed');assert.equal(f.journal.filter(([kind])=>kind==='moderate').length,2);});
test('blocked generated miniature never reaches model POST while safe world can finish partial',async()=>{const f=fixture({moderationReport:images=>report(images,images[0].id==='object'?'block':'allow')}),out=await f.queued(input({photoIntent:'place'}));for(let i=0;i<9;i++)await f.service().tick(`worker-${i}`);assert.equal(f.journal.some(([kind,stage])=>kind==='submit'&&stage==='tripo'),false);assert.equal(f.jobs.get(out.id).assets.reference,undefined);const dto=await f.service().get({id:out.id,token});assert.equal(dto.state,'partial');assert.equal(dto.tripo.state,'failed');});
test('unknown paid submission remains reserved and cannot resubmit after a process restart',async()=>{const f=fixture({submitError:new AppError('SUBMISSION_AMBIGUOUS',502)}),out=await f.queued();await f.service().tick('moderate');await f.service().tick('submit');for(let i=0;i<3;i++)await f.service().tick('restart');assert.equal(f.jobs.get(out.id).state,'submission_uncertain');assert.equal(f.journal.filter(([kind])=>kind==='submit').length,1);assert.equal((await f.service().get({id:out.id,token})).worldlabs.errorCode,'SUBMISSION_AMBIGUOUS');});
test('uncertain sibling never starves polling of a recorded task and never starts an absent stage',async()=>{const f=fixture(),out=await f.queued();await f.service().tick('moderate');const job=f.jobs.get(out.id);job.state='submission_uncertain';job.stages={'tripo-reference':{state:'submission_uncertain',submittedAt:'now'},worldlabs:{state:'processing',taskId:'known-world',progress:20}};await f.service().advance(out.id,token);assert.deepEqual(f.journal.filter(([kind])=>kind==='poll').map(([,stage,id])=>[stage,id]),[['worldlabs','known-world']]);assert.equal(f.journal.some(([kind])=>kind==='submit'||kind==='providerUpload'),false);assert.equal(f.jobs.get(out.id).state,'submission_uncertain');});
test('parallel invocations share the persistent lease and submit a stage once',async()=>{const f=fixture(),out=await f.queued();await f.service().tick('moderate');await Promise.all([f.service().advance(out.id,token),f.service().advance(out.id,token)]);assert.equal(f.journal.filter(([kind])=>kind==='submit').length,1);assert.equal(f.jobs.get(out.id).stages.worldlabs.taskId,'task-worldlabs');});
test('known task polling retries network failures without replacing ID or repeating POST; moderate checks never invent a floor transform',async()=>{const f=fixture({pollError:new AppError('PROVIDER_NETWORK',502),semantics:{metricScaleFactor:1000,groundPlaneOffset:NaN}}),out=await f.queued();await f.service().tick('moderate');await f.service().tick('world');await f.service().tick('model');const id=f.jobs.get(out.id).stages.tripo.taskId;await f.service().tick('network');assert.equal(f.jobs.get(out.id).stages.tripo.taskId,id);assert.equal(f.journal.filter(([kind])=>kind==='submit').length,2);const job=f.jobs.get(out.id);job.document.worldSemantics={metricScaleFactor:1000,groundPlaneOffset:0};assert.equal((await f.service().get({id:out.id,token})).generation.worldlabs.worldSemantics,undefined);});
test('disabled generation, unavailable moderation and exhausted database budget close create but retain example catalog',async()=>{for(const options of[{enabled:false},{moderatorConfigured:false},{canCreate:false}]){const f=fixture(options),status=await f.service().status();assert.equal(status.storage,'cloud');assert.equal(status.localOnly,false);assert.equal(status.available,false);assert.ok(status.examples.length>=3);if(options.enabled===false||options.moderatorConfigured===false)await rejectCode(f.service().prepare(input(),'c'.repeat(64)),'GENERATION_PAUSED');assert.equal(f.journal.some(([kind])=>kind==='submit'),false);}});
test('generated outputs cannot exceed the reserved100MiB before any storage write',async()=>{const f=fixture(),out=await f.queued();await f.service().tick('moderate');await f.service().tick('world');await f.service().tick('model');const job=f.jobs.get(out.id);job.assets['generated-world']={id:'generated-world',path:`${out.id}/generated/${'c'.repeat(64)}.spz`,mime:'application/octet-stream',bytes:100*1024*1024,sha256:'c'.repeat(64)};const stored=f.journal.filter(([kind])=>kind==='store').length;await f.service().tick('model-complete');assert.equal(f.journal.filter(([kind])=>kind==='store').length,stored);assert.equal(f.jobs.get(out.id).stages.tripo.state,'failed');assert.equal(f.jobs.get(out.id).stages.tripo.errorCode,'GENERATED_ASSET_SIZE_LIMIT');assert.equal(f.journal.filter(([kind])=>kind==='submit').length,2);});
