import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {dirname,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {setImmediate} from 'node:timers/promises';
let require=createRequire(import.meta.url);try{require.resolve('typescript');}catch{require=createRequire((process.env.GIFTPORTALS_TEST_APP_ROOT||'C:/Users/admin/Documents/Codex/2026-09-29/co/work/hackador-tripothon/projects/giftportals')+'/package.json');}
const ts=require('typescript'),threeUrl=pathToFileURL(resolve(dirname(require.resolve('three')),'three.module.js')).href,THREE=await import(threeUrl),url=source=>'data:text/javascript;base64,'+Buffer.from(source).toString('base64');
const transpile=source=>ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
const canonical=process.env.GIFTPORTALS_TEST_APP_ROOT||'C:/Users/admin/Documents/Codex/2026-09-29/co/work/hackador-tripothon/projects/giftportals';
const source=async name=>readFile(existsSync(new URL('../src/'+name,import.meta.url))?new URL('../src/'+name,import.meta.url):resolve(canonical,'src',name),'utf8');
const viewer=url(transpile(await source('viewer-runtime.ts'))),collectionSource=await source('collection-scene.ts');
// Use the existing validator itself; omit unrelated collection scene/GPU code.
const validator=url(transpile('const MAX_IMAGE_PIXELS=16_777_216;\n'+collectionSource.slice(collectionSource.indexOf('function imageDimensions'),collectionSource.indexOf('interface ConveyorItem'))));
const moduleCode=transpile(await source('keepsake-xr.ts')).replace("import './keepsake-xr.css';",'').replace("'./viewer-runtime'",JSON.stringify(viewer)).replace("import('three')",`import(${JSON.stringify(threeUrl)})`).replace("import('three/addons/loaders/GLTFLoader.js')",`import(${JSON.stringify(pathToFileURL(require.resolve('three/addons/loaders/GLTFLoader.js')).href)})`).replace("import('./collection-scene')",`import(${JSON.stringify(validator)})`);
const xr=await import(url(moduleCode)),flush=async()=>{await setImmediate();await setImmediate();},deferred=()=>{let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no;});return{promise,resolve,reject};};
const studioURL='https://gift.example/assets/v10/memory-studio-mobile.spz',memoryURL='https://gift.example/test-assets/memory.spz';
// Use the generated room's actual payload at the transport boundary; Spark decoding and the headset remain mocks.
const roomSPZ=new Uint8Array(await readFile(new URL('../public/assets/v10/memory-studio-mobile.spz',import.meta.url)));
function triangleGLB(){
 const data={asset:{version:'2.0'},buffers:[{byteLength:42}],bufferViews:[{buffer:0,byteOffset:0,byteLength:36},{buffer:0,byteOffset:36,byteLength:6}],accessors:[{bufferView:0,componentType:5126,count:3,type:'VEC3',min:[-.1,0,0],max:[.1,.2,0]},{bufferView:1,componentType:5123,count:3,type:'SCALAR'}],meshes:[{primitives:[{attributes:{POSITION:0},indices:1}]}],nodes:[{mesh:0}],scenes:[{nodes:[0]}],scene:0};
 const encoded=new TextEncoder().encode(JSON.stringify(data)),length=(encoded.length+3)&~3,bytes=new Uint8Array(20+length+8+44),view=new DataView(bytes.buffer);view.setUint32(0,0x46546c67,true);view.setUint32(4,2,true);view.setUint32(8,bytes.length,true);view.setUint32(12,length,true);view.setUint32(16,0x4e4f534a,true);bytes.fill(32,20,20+length);bytes.set(encoded,20);view.setUint32(20+length,44,true);view.setUint32(24+length,0x004e4942,true);new Float32Array(bytes.buffer,28+length,9).set([-.1,0,0,.1,0,0,0,.2,0]);new Uint16Array(bytes.buffer,64+length,3).set([0,1,2]);return bytes;
}
async function fixture(action,settings={}){
 const names=['document','window','navigator','location','isSecureContext','fetch',...(settings.fakeTimers?['setTimeout','clearTimeout']:[])],previous=new Map(names.map(name=>[name,Object.getOwnPropertyDescriptor(globalThis,name)]));
 const state={current:true,runtimeLoads:0,gpus:0,fetches:0,requests:0,started:0,exits:0,models:[],renderers:[],sessions:[],worlds:[],worldFetches:[],worldLoads:[]};
 class Element extends EventTarget{isConnected=true;disabled=false;hidden=false;textContent='';clientWidth=360;clientHeight=240;children=[];setAttribute(){}append(value){this.children.push(value);}remove(){this.isConnected=false;}click(){if(!this.disabled)this.dispatchEvent(new Event('click'));}}
 class Panel extends Element{elements=new Map();get innerHTML(){return this.html||'';}set innerHTML(html){this.html=html;for(const[,name,attrs]of html.matchAll(/<\w+\b[^>]*?(data-kx-[\w-]+)([^>]*)>/g)){const item=new Element();item.hidden=attrs.includes('hidden');item.disabled=attrs.includes('disabled');this.elements.set('['+name+']',item);}}querySelector(selector){return this.elements.get(selector);}}
 class Session extends EventTarget{visibilityState='visible';ended=0;async end(){this.ended++;this.dispatchEvent(new Event('end'));}async requestReferenceSpace(type){if(settings.noFloor&&type==='local-floor')throw new Error('no floor');return{};}}
 state.newSession=()=>{const session=new Session();state.sessions.push(session);return session;};
 const host=new Element(),document={createElement:()=>state.panel=new Panel()},window=new EventTarget();
 const xrSystem={async isSessionSupported(mode){assert.equal(mode,'immersive-vr');return settings.supported!==false;},requestSession(mode,config){state.requests++;assert.equal(mode,'immersive-vr');assert.deepEqual(config,{optionalFeatures:['local-floor']});if(settings.denied)return Promise.reject(new Error('denied'));return settings.sessionPromise||Promise.resolve(state.newSession());}};
 const values={document,window,navigator:settings.noXR?{}:{xr:xrSystem},location:{origin:'https://gift.example'},isSecureContext:settings.insecure?false:true,fetch:async()=>{throw new Error('NETWORK_DISABLED_IN_XR_TEST');}};
 if(settings.fakeTimers){let next=0;state.timers=new Map();values.setTimeout=(callback,ms)=>{const id=++next;state.timers.set(id,{callback,ms});return id;};values.clearTimeout=id=>state.timers.delete(id);state.expire=()=>{const entry=[...state.timers.entries()].find(([,value])=>value.ms===45000);assert.ok(entry);state.timers.delete(entry[0]);entry[1].callback();};}
 for(const[name,value]of Object.entries(values))Object.defineProperty(globalThis,name,{value,configurable:true,writable:true});
 const actualRuntime=await xr.loadKeepsakeXRRuntime();
 const runtime={...actualRuntime,createRenderer(){assert.equal(state.started,state.gpus+1,'parent GPU must be released before each XR GPU starts');state.gpus++;const controllers=[new THREE.Group(),new THREE.Group()],renderer={domElement:new Element(),xr:{enabled:false,getController:i=>controllers[i],setReferenceSpaceType:type=>state.referenceType=type,setFramebufferScaleFactor(){},async setSession(){if(settings.setSessionPromise)await settings.setSessionPromise;}},setPixelRatio(){},setSize(){},setAnimationLoop(callback){this.loop=callback;},render(scene){scene.updateMatrixWorld(true);this.lastScene=scene;this.renders=(this.renders||0)+1;},disposed:0,lost:0,dispose(){this.disposed++;},forceContextLoss(){this.lost++;},controllers};state.renderers.push(renderer);return renderer;},async loadModel(bytes){const model=await(settings.modelPromise||actualRuntime.loadModel(bytes));state.models.push(model);return model;},async loadWorld(renderer,bytes){
  assert.ok(renderer,'a live XR renderer is required before decoding a world');assert.equal(renderer.disposed,0);assert.equal(bytes,roomSPZ,'the generated SPZ payload must reach the runtime unchanged');
  const index=state.worldLoads.length;state.worldLoads.push({renderer,bytes});
  const object=new THREE.Group(),geometry=new THREE.BufferGeometry(),material=new THREE.MeshBasicMaterial();object.add(new THREE.Mesh(geometry,material));
  const world={object,disposed:0,geometryDisposals:0,materialDisposals:0,destroy(){if(this.disposed)return;this.disposed++;object.removeFromParent();geometry.dispose();material.dispose();object.clear();}};
  geometry.addEventListener('dispose',()=>world.geometryDisposals++);material.addEventListener('dispose',()=>world.materialDisposals++);state.worlds.push(world);
  try{if(settings.worldPromises?.[index])await settings.worldPromises[index];if(settings.failWorldAt===index)throw new Error('WORLD_DECODE_FAILED');return world;}catch(error){world.destroy();throw error;}
 }};
 const dependencies={async loadRuntime(){state.runtimeLoads++;return settings.runtimePromise?await settings.runtimePromise:runtime;},async fetchBytes(value,signal){state.fetches++;state.signal=signal;if(value==='https://gift.example/api/instant-cloud?action=asset&opaque=synthetic')return settings.bytes||triangleGLB();assert.ok(value===studioURL||value===memoryURL,'only the expected studio or memory URL may be fetched');const index=state.worldFetches.length;state.worldFetches.push({url:value,signal});if(settings.worldFetchPromises?.[index])await settings.worldFetchPromises[index];return roomSPZ;}};
 state.runtime=runtime;state.host=host;state.handle=xr.mountKeepsakeXR(host,{modelUrl:'/api/instant-cloud?action=asset&opaque=synthetic',title:'My actual keepsake',worldUrl:settings.worldUrl,worldScale:settings.worldScale,modelYaw:settings.modelYaw,isCurrent:()=>state.current,onSessionStarting(){state.started++;},onExit(){state.exits++;}},dependencies);state.element=key=>state.panel.querySelector(`[data-kx-${key}]`);
 try{await flush();await action(state);}finally{state.handle.destroy();await flush();for(const[name,descriptor]of previous)if(descriptor)Object.defineProperty(globalThis,name,descriptor);else delete globalThis[name];}
}
test('unsupported and insecure browsers allocate no GPU, fetch, runtime or XR permission request',async()=>{
 for(const settings of[{supported:false},{noXR:true},{insecure:true}])await fixture(async state=>{assert.equal(state.element('enter').disabled,true);assert.match(state.element('status').textContent,/ordinary 3D gift/);assert.equal(state.requests+state.gpus+state.fetches+state.runtimeLoads,0);assert.equal(state.started+state.exits,0);},settings);
});
test('a keepsake without a world offers only its real souvenir in VR and never promises or loads a World Labs memory',async()=>fixture(async state=>{
 assert.match(state.panel.innerHTML,/Hold your keepsake in VR/);assert.match(state.panel.innerHTML,/A world is unavailable for this gift/);
 assert.doesNotMatch(state.panel.innerHTML,/second opens its World Labs|Real Tripo and World Labs assets/);
 assert.equal(state.element('portal').hidden,true);state.element('enter').click();await flush();await flush();
 assert.equal(state.models.length,1);assert.equal(state.worldFetches.length,0);assert.equal(state.worldLoads.length,0);assert.equal(state.element('portal').hidden,true);
 const renderer=state.renderers[0];renderer.controllers[1].dispatchEvent({type:'select'});state.element('portal').click();await flush();
 assert.equal(state.worldFetches.length,0);assert.equal(state.worldLoads.length,0);assert.equal(state.requests,1);
 state.element('exit').click();assert.equal(state.exits,1);assert.equal(renderer.disposed,1);
}));
test('accepted explicit click loads and displays the actual GLB, controller ray turns only a hit, XR hide pauses draws, cleanup once',async()=>fixture(async state=>{
 assert.equal(state.requests,0);state.element('enter').click();state.element('enter').click();await flush();await flush();assert.equal(state.requests,1);assert.equal(state.gpus,1);assert.equal(state.fetches,1);assert.equal(state.started,1);assert.equal(state.models.length,1);assert.match(state.element('status').textContent,/Look around/);
 const renderer=state.renderers[0];renderer.loop();const scene=renderer.lastScene,room=scene.children.find(value=>value instanceof THREE.Group),gift=room.children.find(value=>value instanceof THREE.Group);assert.ok(gift);assert.equal(new THREE.Box3().setFromObject(gift).getSize(new THREE.Vector3()).y.toFixed(2),'0.42');
 renderer.controllers[0].position.set(0,1.04,0);const before=gift.rotation.y;renderer.controllers[0].dispatchEvent({type:'select'});assert.ok(gift.rotation.y>before);renderer.controllers[0].position.x=4;const rotated=gift.rotation.y;renderer.controllers[0].dispatchEvent({type:'select'});assert.equal(gift.rotation.y,rotated);
 state.sessions[0].visibilityState='hidden';renderer.loop();assert.equal(renderer.renders,1);state.sessions[0].visibilityState='visible';renderer.loop();assert.equal(renderer.renders,2);
 state.element('exit').click();state.handle.destroy();assert.equal(state.sessions[0].ended,1);assert.equal(renderer.disposed,1);assert.equal(renderer.lost,1);assert.equal(renderer.loop,null);assert.equal(state.signal.aborted,true);assert.equal(state.exits,1);
}));
test('declined permissions keep ordinary viewer and never create a GPU or transmit model',async()=>fixture(async state=>{state.element('enter').click();await flush();assert.equal(state.requests,1);assert.equal(state.gpus+state.fetches+state.started+state.exits,0);assert.equal(state.element('enter').disabled,false);assert.match(state.element('status').textContent,/declined/);},{denied:true}));
test('late session permission after destruction is ended once without GPU or parent switch',async()=>{const pending=deferred();await fixture(async state=>{state.element('enter').click();state.handle.destroy();const session=state.newSession();pending.resolve(session);await flush();assert.equal(session.ended,1);assert.equal(state.gpus+state.fetches+state.started+state.exits,0);},{sessionPromise:pending.promise});});
test('cancel during pending permission prevents late acceptance from switching the gift renderer',async()=>{const pending=deferred();await fixture(async state=>{state.element('enter').click();state.element('exit').click();assert.equal(state.element('enter').disabled,false);const session=state.newSession();pending.resolve(session);await flush();assert.equal(session.ended,1);assert.equal(state.started+state.exits+state.gpus,0);assert.match(state.element('status').textContent,/cancelled/);},{sessionPromise:pending.promise});});
test('late runtime after session ended creates no GPU and cannot revive the view',async()=>{const pending=deferred();await fixture(async state=>{state.element('enter').click();await flush();assert.equal(state.started,1);await state.sessions[0].end();pending.resolve(state.runtime);await flush();assert.equal(state.gpus+state.fetches,0);assert.equal(state.exits,1);},{runtimePromise:pending.promise});});
test('late real parsed model is disposed after exit and never attached; local reference space fallback works',async()=>{const pending=deferred();await fixture(async state=>{state.element('enter').click();await flush();assert.equal(state.referenceType,'local');state.element('exit').click();const model=await(await xr.loadKeepsakeXRRuntime()).loadModel(triangleGLB());let disposed=0;model.traverse(object=>object.geometry?.addEventListener('dispose',()=>disposed++));pending.resolve(model);await flush();assert.equal(disposed,1);assert.equal(state.exits,1);assert.equal(state.renderers[0].disposed,1);},{modelPromise:pending.promise,noFloor:true});});
test('45-second loading deadline ends accepted session; late runtime allocates no GPU',async()=>{const pending=deferred();await fixture(async state=>{state.element('enter').click();await flush();state.expire();assert.equal(state.sessions[0].ended,1);assert.equal(state.exits,1);assert.match(state.element('status').textContent,/too long/);pending.resolve(state.runtime);await flush();assert.equal(state.gpus,0);assert.equal(state.timers.size,0);},{runtimePromise:pending.promise,fakeTimers:true});});
test('native headset end and page exit release render loop/context and notify the parent only once',async()=>fixture(async state=>{state.element('enter').click();await flush();await flush();await state.sessions[0].end();window.dispatchEvent(new Event('pagehide'));assert.equal(state.exits,1);assert.equal(state.renderers[0].disposed,1);assert.equal(state.renderers[0].loop,null);assert.equal(state.sessions[0].ended,1);}));
test('malformed or over-budget actual GLB fails closed and restores ordinary viewer',async()=>{
 for(const bytes of[new Uint8Array([1,2,3]),new Uint8Array(25*1024*1024+1)])await fixture(async state=>{state.element('enter').click();await flush();await flush();assert.equal(state.exits,1);assert.equal(state.sessions[0].ended,1);assert.equal(state.renderers[0].disposed,1);assert.match(state.element('status').textContent,/could not open/);},{bytes});
});
test('display normalization preserves original geometry/transforms and disposes shared resources once',()=>{
 const geometry=new THREE.BoxGeometry(2,4,2),material=new THREE.MeshStandardMaterial(),source=new THREE.Group();source.position.set(2,3,4);const a=new THREE.Mesh(geometry,material),b=new THREE.Mesh(geometry,material);source.add(a,b);const before=source.toJSON(),display=xr.createKeepsakeXRDisplay(source,THREE,.7);assert.deepEqual(source.toJSON(),before);assert.equal(source.parent,null);assert.equal(display.rotation.y,.7);assert.ok(Math.abs(new THREE.Box3().setFromObject(display).min.y-.9043136)<1e-6);let gd=0,md=0;geometry.addEventListener('dispose',()=>gd++);material.addEventListener('dispose',()=>md++);xr.disposeKeepsakeXRResources(display,THREE);assert.equal(gd,1);assert.equal(md,1);assert.equal(display.children.length,0);
});

async function enterLoaded(state){state.element('enter').click();await flush();await flush();assert.equal(state.models.length,1);const renderer=state.renderers[0];renderer.loop();const scene=renderer.lastScene,room=scene.children.find(object=>object instanceof THREE.Group&&object.children.some(child=>child instanceof THREE.HemisphereLight)),gift=room.children.find(object=>object instanceof THREE.Group);assert.ok(gift);return{renderer,scene,room,gift};}
const releaseCounts=world=>[world.disposed,world.geometryDisposals,world.materialDisposals];

test('actual generated SPZ reaches XR, controller and button round trips replace studio and memory twice without leaking environments',async()=>fixture(async state=>{
 const{renderer,scene,gift}=await enterLoaded(state);assert.ok(roomSPZ.byteLength>1_000_000);assert.equal(state.worlds.length,1);assert.equal(state.worlds[0].object.parent,scene);assert.equal(state.worlds[0].object.position.y,1.2042749);assert.equal(state.worlds[0].object.scale.x,1.2550683);assert.equal(state.element('portal').hidden,false);assert.equal(gift.visible,true);
 const measuredDesk=new THREE.Vector3(0,-.239,-.95).applyMatrix4(state.worlds[0].object.matrixWorld);assert.ok(measuredDesk.distanceTo(gift.getWorldPosition(new THREE.Vector3()))<1e-6,'the gift base must match the measured provider desk in physical units');
 for(let turn=0;turn<4;turn++){
  if(turn%2===0)renderer.controllers[1].dispatchEvent({type:'select'});else state.element('portal').click();
  await flush();const memory=turn%2===0,current=state.worlds.at(-1);assert.equal(current.object.parent,scene);assert.equal(gift.visible,!memory);assert.equal(current.object.scale.x,memory?1.1601067:1.2550683);assert.equal(current.object.position.y,memory?1.6:1.2042749);assert.match(state.element('portal').textContent,memory?/Return to the desk/:/Step into the memory/);assert.equal(state.element('portal').disabled,false);
  for(const prior of state.worlds.slice(0,-1)){assert.deepEqual(releaseCounts(prior),[1,1,1]);assert.equal(prior.object.parent,null);}
 }
 assert.deepEqual(state.worldFetches.map(item=>item.url),[studioURL,memoryURL,studioURL,memoryURL,studioURL]);assert.equal(state.worldLoads.length,5);assert.equal(state.exits,0);state.element('exit').click();for(const world of state.worlds)assert.deepEqual(releaseCounts(world),[1,1,1]);assert.equal(renderer.disposed,1);assert.equal(state.sessions[0].ended,1);assert.equal(state.exits,1);
},{worldUrl:'/test-assets/memory.spz',worldScale:1.1601067}));

test('squeezing a controller hit grabs the actual souvenir, follows its pose, releases on the desk and ignores misses or memory mode',async()=>fixture(async state=>{
 const{renderer,room,gift}=await enterLoaded(state),controller=renderer.controllers[0];controller.position.set(0,1.04,0);renderer.loop();const original=gift.getWorldPosition(new THREE.Vector3());controller.dispatchEvent({type:'squeezestart'});assert.equal(gift.parent,controller);assert.ok(gift.getWorldPosition(new THREE.Vector3()).distanceTo(original)<1e-6);
 controller.position.x=.3;renderer.loop();assert.ok(Math.abs(gift.getWorldPosition(new THREE.Vector3()).x-original.x-.3)<1e-6);controller.dispatchEvent({type:'squeezeend'});assert.equal(gift.parent,room);assert.deepEqual(gift.position.toArray(),[0,.9043136,-1.1923149]);assert.equal(gift.rotation.y,.35);
 controller.position.x=4;renderer.loop();controller.dispatchEvent({type:'squeezestart'});assert.equal(gift.parent,room);renderer.controllers[1].dispatchEvent({type:'select'});await flush();controller.position.x=0;renderer.loop();controller.dispatchEvent({type:'squeezestart'});assert.equal(gift.visible,false);assert.equal(gift.parent,room);
},{worldUrl:'/test-assets/memory.spz',modelYaw:.35}));

test('a failed memory decode preserves the current studio and keeps the gift interactive',async()=>fixture(async state=>{
 const{renderer,scene,room,gift}=await enterLoaded(state),studio=state.worlds[0];state.element('portal').click();await flush();assert.equal(state.worlds.length,2);assert.deepEqual(releaseCounts(state.worlds[1]),[1,1,1]);assert.deepEqual(releaseCounts(studio),[0,0,0]);assert.equal(studio.object.parent,scene);assert.equal(gift.visible,true);assert.equal(gift.parent,room);assert.match(state.element('status').textContent,/world could not open/);assert.equal(state.element('portal').disabled,false);assert.equal(renderer.disposed,0);assert.equal(state.exits,0);
 renderer.controllers[0].position.set(0,1.04,0);renderer.loop();const before=gift.rotation.y;renderer.controllers[0].dispatchEvent({type:'select'});assert.ok(gift.rotation.y>before);
},{worldUrl:'/test-assets/memory.spz',failWorldAt:1}));

test('an in-flight world replacement rejects duplicate input and disposes its late decoded resources after headset exit',async()=>{
 const pending=deferred();await fixture(async state=>{
  const{renderer,gift}=await enterLoaded(state);state.element('portal').click();await flush();assert.equal(state.worldLoads.length,2);assert.equal(state.element('portal').disabled,true);state.element('portal').click();renderer.controllers[1].dispatchEvent({type:'select'});assert.equal(state.worldFetches.length,2);renderer.controllers[0].position.set(0,1.04,0);renderer.loop();const parent=gift.parent;renderer.controllers[0].dispatchEvent({type:'squeezestart'});assert.equal(gift.parent,parent);
  state.element('exit').click();assert.equal(state.worldFetches.at(-1).signal.aborted,true);assert.deepEqual(releaseCounts(state.worlds[0]),[1,1,1]);assert.deepEqual(releaseCounts(state.worlds[1]),[0,0,0]);pending.resolve();await flush();assert.deepEqual(releaseCounts(state.worlds[1]),[1,1,1]);assert.equal(state.worlds[1].object.parent,null);assert.equal(renderer.loop,null);assert.equal(renderer.disposed,1);assert.equal(state.exits,1);assert.equal(state.element('portal').hidden,true);
 },{worldUrl:'/test-assets/memory.spz',worldPromises:[undefined,pending.promise]});
});

test('a studio fetch resolving after native session end cannot decode into a released GPU',async()=>{
 const pending=deferred();await fixture(async state=>{
  const{renderer}=await enterLoaded(state);assert.equal(state.worldFetches.length,1);assert.equal(state.worldLoads.length,0);await state.sessions[0].end();assert.equal(state.worldFetches[0].signal.aborted,true);pending.resolve();await flush();assert.equal(state.worldLoads.length,0);assert.equal(state.worlds.length,0);assert.equal(renderer.disposed,1);assert.equal(renderer.loop,null);assert.equal(state.exits,1);
 },{worldUrl:'/test-assets/memory.spz',worldFetchPromises:[pending.promise]});
});

test('world transforms use local reference space fallback and a second XR session gets an independent studio lifecycle',async()=>fixture(async state=>{
 const first=await enterLoaded(state);assert.equal(state.referenceType,'local');assert.equal(first.room.position.y,-1.6);assert.equal(state.worlds[0].object.position.y,1.2042749-1.6);state.element('exit').click();assert.deepEqual(releaseCounts(state.worlds[0]),[1,1,1]);state.element('enter').click();await flush();await flush();assert.equal(state.gpus,2);assert.equal(state.started,2);assert.equal(state.worldLoads.length,2);assert.equal(state.worlds[1].object.position.y,1.2042749-1.6);assert.equal(state.worlds[1].disposed,0);state.element('portal').click();await flush();assert.deepEqual(state.worldFetches.map(item=>item.url),[studioURL,studioURL,memoryURL]);assert.deepEqual(releaseCounts(state.worlds[1]),[1,1,1]);state.element('exit').click();assert.deepEqual(releaseCounts(state.worlds[2]),[1,1,1]);assert.equal(state.exits,2);assert.deepEqual(state.sessions.map(session=>session.ended),[1,1]);assert.deepEqual(state.renderers.map(renderer=>renderer.disposed),[1,1]);
},{worldUrl:'/test-assets/memory.spz',noFloor:true}));
