/** Artistic requests do not replace actual geometry, moderation or collider checks. */
export const GIFT_ART_STYLE_VERSION='giftportals-cinematic-v10';
export const WORLD_ART_PROMPT_VERSION='giftportals-world-photographic-v11';
export const SOUVENIR_ART_PROMPT_VERSION='giftportals-souvenir-cinematic-v10-compact1';
export const GIFT_ART_STYLE='Required art direction: physically realistic cinematic physical detail, believable material finish, richly resolved geometry and a refined travel-collectible aesthetic. Use coherent natural colors, muted navy blue and cream, warm wood grain and brass, clear water and soft sky blues. Preserve the distinctive shapes and proportions of the supplied reference, with complete three-dimensional forms and readable depth. Resolve fine surface textures, crisp architectural details, contact shadows and convincing reflected light. Do not simplify objects into low-detail primitives or flatten the environment into a painted backdrop. Do not apply a global oil-paint, ink-outline or pastel illustration treatment.';
export const GIFT_ART_LIGHTING='Use soft natural light or warm practical interior lamps balanced with cool ambient sky light. Preserve detail in highlights and shadows with realistic light falloff, subtle reflections and grounded contact shadows. Keep the atmosphere inviting and calm; avoid harsh saturation, heavy bloom, opaque haze or glowing effects that hide the geometry. Keep foreground shapes, walking surfaces and structural edges legible.';

/** World direction is independent of the miniature's collectible styling. */
export const WORLD_REALISM_STYLE='Reconstruct a sharp photographic three-dimensional place at real human scale. Preserve perspective, landmark silhouettes, relative positions, proportions, construction, terrain and visible materials. Resolve masonry joints, structural edges, branches, foliage, metal, glass and water reflections with physical depth. Use actual scene colors and textures, without a brand palette or collectible finish. Rebuild separate spatial forms with side surfaces, openings, occlusion and grounded contact, never a flat projected backdrop. Infer unseen surfaces plausibly. Do not imitate brushwork, drawing, illustration, stylized rendering or miniature scenery.';
export const WORLD_REALISM_LIGHTING='Match real daylight, sky, exposure, shadows and material response. Keep crisp detail at every visible distance, with natural atmospheric depth. Maintain reflected light, clear water and grounded shadows. Avoid heavy bloom, blur, opaque mist, decorative glow, exaggerated saturation and synthetic color grading.';
