export interface CuriosityFact { id:string; title:string; text:string; sourceTitle:string; sourceUrl:string; subject:'object'|'region'; regionId?:string; objectHint?:string }
export const CURIOSITY_REGIONS = [
 {id:'rio',label:'Rio de Janeiro, Brazil',latitude:-22.91,longitude:-43.17},
 {id:'sao-paulo',label:'São Paulo, Brazil',latitude:-23.55,longitude:-46.63},
 {id:'kyoto',label:'Kyoto, Japan',latitude:35.01,longitude:135.77},
 {id:'paris',label:'Paris, France',latitude:48.86,longitude:2.35},
 {id:'new-york',label:'New York, United States',latitude:40.71,longitude:-74.01},
 {id:'cairo',label:'Cairo, Egypt',latitude:30.04,longitude:31.24},
 {id:'seoul',label:'Seoul, South Korea',latitude:37.5665,longitude:126.9780},
 // Public reference viewpoint for the Geunjeongjeon photo, not device GPS.
 {id:'gyeongbokgung-palace',label:'Gyeongbokgung Palace, Seoul, South Korea',latitude:37.578472,longitude:126.977337},
];
// Reviewed primary museum, municipal and heritage sources. These facts describe a
// category or place, never authenticate, date or appraise the photographed object.
export const CURIOSITY_FACTS:readonly CuriosityFact[] = [
 {id:'rio-gardens',subject:'region',regionId:'rio',title:'A garden older than the postcard',text:'Rio’s Botanical Gardens were established in 1808. UNESCO includes them in the city’s cultural landscape, where mountains, gardens and the sea shape everyday life.',sourceTitle:'UNESCO — Carioca Landscapes',sourceUrl:'https://whc.unesco.org/en/list/1100/'},
 {id:'sao-paulo-park',subject:'region',regionId:'sao-paulo',title:'A birthday gift to a city',text:'Ibirapuera Park opened on 21 August 1954 during celebrations of São Paulo’s 400th anniversary.',sourceTitle:'São Paulo City — Ibirapuera',sourceUrl:'https://www.prefeitura.sp.gov.br/web/meio_ambiente/w/parques/regiao_sul/14062'},
 {id:'kyoto-gardens',subject:'region',regionId:'kyoto',title:'Gardens with a long memory',text:'Founded in 794, Kyoto served as Japan’s imperial capital until the middle of the 19th century. Its historic gardens influenced landscape gardening around the world.',sourceTitle:'UNESCO — Historic Monuments of Ancient Kyoto',sourceUrl:'https://whc.unesco.org/en/list/688/'},
 {id:'paris-seine',subject:'region',regionId:'paris',title:'A river through many chapters',text:'The banks of the Seine bring together layers of Parisian history, including the Louvre, Notre-Dame and the Eiffel Tower. UNESCO recognizes this riverside ensemble as World Heritage.',sourceTitle:'UNESCO — Paris, Banks of the Seine',sourceUrl:'https://whc.unesco.org/en/list/600/'},
 {id:'new-york-liberty',subject:'region',regionId:'new-york',title:'A gift that became a landmark',text:'The Statue of Liberty was a gift of friendship from the people of France to the United States. It was dedicated in New York Harbor on 28 October 1886.',sourceTitle:'National Park Service — Statue of Liberty facts',sourceUrl:'https://www.nps.gov/stli/learn/statue-of-liberty-facts.htm'},
 {id:'new-york-bridge',subject:'region',regionId:'new-york',title:'Two sides, one shared crossing',text:'The Brooklyn Bridge links Manhattan and Brooklyn across the East River. Construction began in 1869 and was completed in 1883, creating a landmark that still shapes the city’s skyline.',sourceTitle:'NYC Department of Transportation — Brooklyn Bridge',sourceUrl:'https://www.nyc.gov/html/dot/html/infrastructure/brooklyn-bridge.shtml'},
 {id:'cairo-history',subject:'region',regionId:'cairo',title:'A city with many layers',text:'Historic Cairo was founded in the tenth century. Its surviving mosques, schools, fountains and urban fabric preserve many chapters of the city’s history.',sourceTitle:'UNESCO — Historic Cairo',sourceUrl:'https://whc.unesco.org/en/list/89/'},
 {id:'cairo-pyramids',subject:'region',regionId:'cairo',title:'A wider landscape of ancient memory',text:'The pyramids at Giza belong to a UNESCO World Heritage property that includes Memphis and pyramid fields extending to Dahshur. This artistic scene is inspired by that landscape; it does not document a real visit.',sourceTitle:'UNESCO — Memphis and its Necropolis',sourceUrl:'https://whc.unesco.org/en/list/86/'},
 {id:'antikythera-calendar',subject:'object',objectHint:'antikythera',title:'Questions about the sky, answered in gears',text:'The National Archaeological Museum dates the Antikythera Mechanism to around 150–100 BC and describes it as a portable mechanical computer for astronomical and calendar calculations. This gift is an artistic reference, not an authenticated reconstruction.',sourceTitle:'National Archaeological Museum — Collection guide',sourceUrl:'https://www.namuseum.gr/wp-content/uploads/2022/03/nam-brochure-%CE%95%CE%9D-low.pdf'},
 {id:'astrolabe-cultures',subject:'object',objectHint:'astrolabe',title:'A sky shared across cultures',text:'A medieval European astrolabe in Royal Museums Greenwich combines Europeanized Arabic and Latin star names. It offers a small example of astronomical knowledge travelling between cultures. This gift is an artistic reference.',sourceTitle:'Royal Museums Greenwich — Astrolabe AST0558',sourceUrl:'https://www.rmg.co.uk/collections/objects/rmgc-object-10720'},
 {id:'voyager-message',subject:'object',objectHint:'voyager-golden-record',title:'A message for somewhere far away',text:'NASA placed a Golden Record on each Voyager spacecraft. The gold-plated copper records carry selected sounds and images portraying life and culture on Earth. This gift is an artistic reference to that message.',sourceTitle:'NASA — Golden Record overview',sourceUrl:'https://science.nasa.gov/mission/voyager/voyager-golden-record-overview/'},
 {id:'apollo-return',subject:'object',objectHint:'apollo-capsule',title:'The part that brought them home',text:'Apollo 11’s command module Columbia returned its three astronauts to the Pacific Ocean on 24 July 1969. It was the only part of the spacecraft that returned to Earth. This gift is an artistic reference.',sourceTitle:'Smithsonian — Apollo 11 command module',sourceUrl:'https://airandspace.si.edu/amp-stories/command-module-and-graffiti/index.html'},
 {id:'printing-pages',subject:'object',objectHint:'printing-press',title:'Ideas, one reusable letter at a time',text:'Gutenberg’s Bible was probably completed in Mainz in late 1455 using movable metal type. The Library of Congress describes it as a turning point in bookmaking. This gift is an artistic reference to early printing.',sourceTitle:'Library of Congress — The Gutenberg Bible',sourceUrl:'https://www.loc.gov/exhibits/bibles/the-gutenberg-bible.html'},
 {id:'clock-pocket',subject:'object',objectHint:'clock',title:'A pocket-sized status symbol',text:'Before the 1920s, pocket watches could signal social status, wealth and education as well as tell the time. This is context about watches, not a date or valuation of your object.',sourceTitle:'Smithsonian — Delkin Pocket Watch',sourceUrl:'https://www.si.edu/object/delkin-pocket-watch%3Anmah_745474'},
 {id:'ceramic-travels',subject:'object',objectHint:'ceramic',title:'A pattern that travelled the world',text:'Blue-and-white ceramics originated in China and were widely traded, copied and reimagined by makers worldwide. A similar pattern alone does not prove where a piece was made.',sourceTitle:'V&A — Chinese blue-and-white ceramics',sourceUrl:'https://www.vam.ac.uk/articles/chinese-blue-and-white-ceramics'},
 {id:'camera-snapshots',subject:'object',objectHint:'camera',title:'When snapshots became everyday life',text:'The Kodak camera introduced in 1888 used flexible roll film and helped put photography within reach of ordinary people. This fact does not identify the model or age of your camera.',sourceTitle:'Smithsonian — Original Kodak Camera',sourceUrl:'https://www.americanhistory.si.edu/collections/object/nmah_760118'},
 {id:'bird-feathers',subject:'object',objectHint:'bird',title:'A tiny echo of dinosaurs',text:'Birds evolved from dinosaurs, and feathers existed before they were used for flight. Early feathers may have helped animals display, hide or stay warm.',sourceTitle:'Cornell Lab — Feathers Through Time',sourceUrl:'https://academy.allaboutbirds.org/features/all-about-feathers/feathers-through-time.php'},
];
export function selectedCuriosities(ids:unknown):CuriosityFact[] {
 if(ids===undefined)return [];
 if(!Array.isArray(ids)||ids.length>2||ids.some(x=>typeof x!=='string'||!CURIOSITY_FACTS.some(f=>f.id===x))||new Set(ids).size!==ids.length)throw new Error('CURIOSITY_IDS_INVALID');
 return ids.map(id=>({...CURIOSITY_FACTS.find(f=>f.id===id)!}));
}
export function curiositiesFor(objectHint:string,regionId?:string):CuriosityFact[] {
 return CURIOSITY_FACTS.filter(f=>f.objectHint===objectHint || Boolean(regionId)&&f.regionId===regionId).map(f=>({...f}));
}
