export type InstantPhotoIntent = 'object' | 'place';
export type InstantExampleCategory = 'cities' | 'objects';
export type InstantObjectRepresentation = 'original-object' | 'framed-postcard' | 'derived-object' | 'souvenir-miniature';
export interface InstantSourceAttribution {
  author: string; sourceUrl: string; license: string; licenseUrl: string; changes?: string;
}
export interface InstantExample {
  id: string; title: string; imageUrl: string; worldPrompt: string; worldImageUrl?: string;
  photoIntent?: InstantPhotoIntent; category?: InstantExampleCategory; caption?: string; story?: string;
  curiosityIds?: readonly string[]; regionId?: string; objectHint?: string; readyGiftUrl?: string;
  objectImageUrl?: string; objectImageRole?: 'miniature-reference'; objectRepresentation?: InstantObjectRepresentation;
  sourceAttribution?: InstantSourceAttribution;
}

/** One catalog for the browser and local API. These are original artistic
 * references, not authenticated photographs or scans of museum objects. */
export const INSTANT_EXAMPLES: readonly InstantExample[] = [
  { id: 'rio', title: 'Rio de Janeiro', category: 'cities', photoIntent: 'place', objectRepresentation: 'souvenir-miniature', objectImageUrl: '/assets/portal-dusk/rio-keepsake.png', objectImageRole: 'miniature-reference', regionId: 'rio', imageUrl: '/assets/examples/v11/rio-scene.jpg', worldImageUrl: '/assets/examples/v11/rio-scene.jpg', caption: 'Botafogo Bay · photo by Donatas Dabravolskas · CC BY-SA 4.0', curiosityIds: ['rio-gardens'], readyGiftUrl: '#/generated/rio-example',
    sourceAttribution: { author: 'Donatas Dabravolskas', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Botafogo_Beach_and_the_Sugarloaf_Mountain.jpg', license: 'CC BY-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/', changes: 'Wikimedia resized reference photograph; generated three-dimensional world and inferred unseen surroundings.' },
    worldPrompt: 'Faithfully reconstruct the actual Botafogo Bay scene in the supplied daytime photograph: Sugarloaf Mountain and Morro da Urca with their correct rock silhouettes and green slopes, the blue bay and anchored sailboats, the curved pale beach, shoreline roads, actual apartment buildings, palms and mature trees. Preserve their relative positions, proportions, sunlight and photographic colors. Complete the nearest real beach and shoreline promenade as continuous ground with clearly separated water and visible edges. Do not invent a wooden deck, lanterns, new landmarks or a sunset. No readable text, no people.',
    story: 'Imagine a warm afternoon by the bay, the last light touching the mountains. A little piece of Rio, kept close for someone you love.' },
  { id: 'paris', title: 'Paris by the Seine', category: 'cities', photoIntent: 'place', objectRepresentation: 'souvenir-miniature', objectImageUrl: '/assets/examples/v17/paris-souvenir-reference.png', objectImageRole: 'miniature-reference', regionId: 'paris', imageUrl: '/assets/examples/v11/paris-scene.jpg', worldImageUrl: '/assets/examples/v11/paris-scene.jpg', caption: 'The Seine and Eiffel Tower · photo by Alex Liivet · CC0', curiosityIds: ['paris-seine'], readyGiftUrl: '#/generated/paris-example',
    sourceAttribution: { author: 'Alex Liivet', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Overview_Seine_River_to_Eiffel_Tower_(37578867564).jpg', license: 'CC0 1.0', licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/', changes: 'Original reference photograph; generated three-dimensional world and inferred unseen surroundings.' },
    worldPrompt: 'Faithfully reconstruct the actual Seine riverside in the supplied daytime photograph: the complete Eiffel Tower on the left with recognizable open iron lattice and four legs, the real bridge crossing the river, the moored white river boats, the foreground paved quay and steps with railings and street lamps, leafless trees, and the actual apartment towers on the right. Preserve their relative positions, depth, scale, blue sky, daylight and natural material colors. Continue the nearest real quay as a connected walking surface with railings and a distinct water edge. Do not substitute generic buildings, move the landmark, invent a bench or apply twilight. Remove people and readable lettering while keeping the scene structure.',
    story: 'Imagine a quiet walk along the Seine, with the city and river around you. A little piece of Paris you can keep close and step inside.' },
  { id: 'kyoto', title: 'Kyoto garden', category: 'cities', photoIntent: 'place', objectRepresentation: 'souvenir-miniature', regionId: 'kyoto', imageUrl: '/assets/examples/v13/kyoto.jpg', caption: 'Artistic interpretation · inspired by Kyoto', curiosityIds: ['kyoto-gardens'],
    worldPrompt: 'Reconstruct a photographic Kyoto garden from the visible scene elements. Preserve the dry stone path, wooden pagoda, red maples, moss and calm pond with authentic construction, recognizable foliage and continuous path surfaces. Match natural daylight and the reference proportions. No text, no people.',
    story: 'Imagine a quiet garden in the morning mist, where a small path leads to a moment worth keeping. A little tribute to Kyoto.' },
  { id: 'new-york', title: 'New York in golden light', category: 'cities', photoIntent: 'place', objectRepresentation: 'souvenir-miniature', objectImageUrl: '/assets/examples/v17/new-york-souvenir-reference.png', objectImageRole: 'miniature-reference', regionId: 'new-york', imageUrl: '/assets/examples/v13/new-york.jpg', caption: 'Artistic interpretation · inspired by New York', curiosityIds: ['new-york-bridge'],
    worldPrompt: 'Reconstruct a photographic Brooklyn waterfront from the visible scene elements. Preserve the Manhattan skyline, Brooklyn Bridge structure, East River and broad waterfront overlook with accurate relative positions, independent structural detail and real ground surfaces. Match natural light and believable water reflections. No text, no people.',
    story: 'Imagine a pause by the East River, a bridge joining two sides of a city and a moment connecting two people. A little world for the next chapter.' },
  { id: 'cairo', title: 'Cairo & Giza in golden light', category: 'cities', photoIntent: 'place', objectRepresentation: 'souvenir-miniature', objectImageUrl: '/assets/examples/v17/cairo-souvenir-reference.png', objectImageRole: 'miniature-reference', regionId: 'cairo', imageUrl: '/assets/examples/v13/cairo.jpg', caption: 'Artistic interpretation · inspired by Cairo and Giza', curiosityIds: ['cairo-pyramids'],
    worldPrompt: 'Reconstruct a photographic Cairo-and-Giza courtyard from the visible scene elements. Preserve sandstone construction, shaded arches, palms, the open terrace and the distant pyramid silhouettes with sharp masonry, real foliage, continuous floor surfaces and authentic proportions. Match natural light and materials without a decorative color palette. No text, no people.',
    story: 'Imagine golden light crossing a sandstone courtyard, with the pyramids in the distance. An artistic place for a new story to be shared.' },
  { id: 'antikythera', title: 'Antikythera mechanism', category: 'objects', photoIntent: 'object', objectHint: 'antikythera', imageUrl: '/assets/examples/v13/antikythera.jpg', worldImageUrl: '/assets/examples/v13/antikythera-world.jpg', caption: 'Artistic reference · inspired by ancient astronomical mechanisms', curiosityIds: ['antikythera-calendar'], readyGiftUrl: '#/generated/antikythera-example',
    worldPrompt: 'An imaginative ancient Greek island observatory inspired by astronomical gears. A stone terrace overlooking the Mediterranean, bronze celestial rings, warm lamps, a darkening starry sky and an open path around a low table. A fictional setting celebrating human curiosity. No text, no people.',
    story: 'A little tribute to the people who turned questions about the sky into gears. Imagine carrying that curiosity into a world of your own.' },
  { id: 'astrolabe', title: 'A brass astrolabe', category: 'objects', photoIntent: 'object', objectHint: 'astrolabe', imageUrl: '/assets/examples/v13/astrolabe.jpg', caption: 'Artistic reference · inspired by historical astrolabes', curiosityIds: ['astrolabe-cultures'],
    worldPrompt: 'An imaginative observatory courtyard inspired by a brass astrolabe. Sandstone arches, a low instrument table, geometric floor tiles, warm brass, deep violet evening sky and distant stars. An open space celebrating navigation and knowledge shared across cultures. No text, no people.',
    story: 'A small instrument, a very large sky. Imagine a meeting place for the people who learned to read the stars and share what they found.' },
  { id: 'voyager-golden-record', title: 'Voyager Golden Record', category: 'objects', photoIntent: 'object', objectHint: 'voyager-golden-record', imageUrl: '/assets/examples/v13/voyager-golden-record.jpg', caption: 'Artistic reference · inspired by the Voyager Golden Record', curiosityIds: ['voyager-message'],
    worldPrompt: 'An imaginative quiet space observatory inspired by the Voyager Golden Record. A circular open viewing deck, warm golden light, translucent listening rings, Earth glowing in the distance and a deep star field. A fictional place to leave a personal message for someone far away. No text, no people.',
    story: 'A message sent far beyond home. Imagine making a tiny record of the sounds, memories and people you would want the universe to know.' },
  { id: 'apollo-capsule', title: 'Apollo return capsule', category: 'objects', photoIntent: 'object', objectHint: 'apollo-capsule', imageUrl: '/assets/examples/v13/apollo-capsule.jpg', caption: 'Artistic reference · inspired by Apollo command modules', curiosityIds: ['apollo-return'],
    worldPrompt: 'An imaginative Apollo-inspired lunar observation deck. A quiet broad platform, softly lit control consoles, silver surfaces, warm amber guidance lights and Earth above the horizon. A fictional space for a story about courage and coming home. No text, no people.',
    story: 'A little tribute to a journey that needed a way home. Imagine a place to look back at Earth and remember who is waiting for you.' },
  { id: 'printing-press', title: 'A movable-type press', category: 'objects', photoIntent: 'object', objectHint: 'printing-press', imageUrl: '/assets/examples/v13/printing-press.jpg', caption: 'Artistic reference · inspired by early European printing presses', curiosityIds: ['printing-pages'],
    worldPrompt: 'An imaginative early European print workshop inspired by movable-type printing. Warm timber beams, sunlight through high windows, paper stacks, brass type trays and a broad open aisle around a wooden worktable. A fictional place celebrating ideas shared through books. No readable text, no people.',
    story: 'A small machine that helped ideas travel. Imagine a workshop where the next page could carry a message written just for someone you love.' },
];

export function instantCatalogCategory(examples: readonly InstantExample[], category: InstantExampleCategory): InstantExample[] {
  return examples.filter(example => example.category === category || (!example.category && example.photoIntent === (category === 'cities' ? 'place' : 'object'))).map(example => ({ ...example }));
}
