import './gift-curiosities.css';
import {curiositiesFor,selectedCuriosities,type CuriosityFact} from '../shared/gift-curiosities';
import type {InstantPhotoReport} from './instant-creator-state';
interface Options { getImage(signal:AbortSignal):Promise<string>;getRegion():string|undefined;inspect?(image:string,signal:AbortSignal):Promise<InstantPhotoReport>;isCurrent():boolean;onDecision(decision:'allow'|'block'|'review'|undefined):void;onChange():void;onStory(text:string):void }
export interface GiftCuriosityPreset { objectHint?:string;regionId?:string;factIds:readonly string[];story:string }
export interface GiftCuriositiesHandle { reset():void;preset(value:GiftCuriosityPreset):void;refreshRegion():void;selectedIds():string[];destroy():void }
const esc=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const categories=[['unknown','Choose a category'],['clock','Clock or watch'],['ceramic','Pottery or ceramics'],['camera','Camera'],['book','Book'],['landscape','Landscape or place'],['keepsake','Souvenir or keepsake'],['antikythera','Antikythera-inspired mechanism'],['astrolabe','Astrolabe-inspired instrument'],['voyager-golden-record','Voyager-inspired record'],['apollo-capsule','Apollo-inspired capsule'],['printing-press','Early-printing-inspired press']];
const seeds:Record<string,string>={clock:'If this little clock could speak, which moment would it ask us to keep?',ceramic:'Some things carry their story in a tiny chip or a pattern. What does this one remind you of?',camera:'A small camera, a thousand moments. Which photograph would you take us back to?',landscape:'A place worth keeping close. What happened here that made it yours?',keepsake:'It may look small, but the memory it carries is a whole world.',book:'A book can carry a journey between its covers. Where did this one take you?',unknown:'Every little thing has a story. Where did you find it, and who does it make you think of?'};
export function mountGiftCuriosities(host:HTMLElement,options:Options):GiftCuriositiesHandle {
 const events=new AbortController();let request:AbortController|undefined,epoch=0,dead=false,hint='unknown',inspected=false,selection=new Set<string>(),presetFacts:CuriosityFact[]|undefined,presetRegion:string|undefined,presetStory:string|undefined;
 host.classList.add('gift-curiosities');
 host.innerHTML=`<div class="gc-story-heading"><span aria-hidden="true">✧</span><div><h3>There’s a story in this little thing.</h3><p>Discover a curiosity, or start with a memory.</p></div></div><button type="button" class="gc-discover" data-curio-discover>Discover its story <span aria-hidden="true">↗</span></button><p class="gc-discover-note">${options.inspect ? 'Your photo is checked and analyzed locally. Nothing is sent for this step.' : 'Explore a category while your photo stays on this device. Photos are screened securely when you create.'}</p><p data-curio-status role="status" aria-live="polite"></p><div data-curio-result hidden><label class="gc-category">What does it look like?<select data-curio-category>${categories.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select></label><div data-curio-facts></div><div class="gc-story-seed"><span>STORY IDEA</span><p data-curio-seed></p><button type="button" data-curio-use-seed>Start with this idea</button></div><small class="gc-provenance">Curiosities describe a category or place. A photo cannot prove an object’s age, maker, value or personal history.</small></div>`;
 const button=host.querySelector<HTMLButtonElement>('[data-curio-discover]')!,status=host.querySelector<HTMLElement>('[data-curio-status]')!,result=host.querySelector<HTMLElement>('[data-curio-result]')!,select=host.querySelector<HTMLSelectElement>('[data-curio-category]')!;
 const active=()=>!dead&&host.isConnected&&options.isCurrent();
 function render(){
  const facts=presetFacts?[...presetFacts,...curiositiesFor(hint,options.getRegion()).filter(fact=>!presetFacts!.some(preset=>preset.id===fact.id))]:curiositiesFor(hint,options.getRegion()||presetRegion),ids=new Set(facts.map(x=>x.id));selection=new Set([...selection].filter(x=>ids.has(x)));
  const list=host.querySelector<HTMLElement>('[data-curio-facts]')!;list.replaceChildren();
  for(const fact of facts){const card=document.createElement('article');card.className='gc-fact';card.innerHTML=`<span>${fact.subject==='region'?'FROM YOUR CHOSEN PLACE':'A LITTLE HISTORY'}</span><h4>${esc(fact.title)}</h4><p>${esc(fact.text)}</p><a href="${esc(fact.sourceUrl)}" target="_blank" rel="noopener noreferrer">${esc(fact.sourceTitle)} ↗</a><label><input type="checkbox" ${selection.has(fact.id)?'checked':''}/><span>Add this curiosity to the gift</span></label>`;card.querySelector('input')!.addEventListener('change',event=>{const input=event.target as HTMLInputElement;if(input.checked&&selection.size>=2){input.checked=false;status.textContent='Choose up to two curiosities for this gift.';return;}input.checked?selection.add(fact.id):selection.delete(fact.id);options.onChange();},{signal:events.signal});list.append(card);}
  host.querySelector<HTMLElement>('[data-curio-seed]')!.textContent=presetStory||seeds[hint]||seeds.unknown;
 }
 function reset(){epoch++;request?.abort();request=undefined;inspected=false;hint='unknown';selection.clear();presetFacts=undefined;presetRegion=undefined;presetStory=undefined;select.value='unknown';result.hidden=true;button.disabled=false;button.textContent='Discover its story ↗';status.textContent='';options.onDecision(undefined);}
 button.addEventListener('click',()=>{
  if(!active()||button.disabled)return;if(!options.inspect){inspected=true;result.hidden=false;hint=select.value;render();status.textContent='Choose a category to explore its history. Your photo will be screened securely when you create.';options.onDecision(undefined);return;}const attempt=++epoch;request?.abort();request=new AbortController();const signal=request.signal;
  button.disabled=true;button.textContent='Looking a little closer…';status.textContent='Checking your photo locally before looking for its story.';
  void(async()=>{try{
   const image=await options.getImage(signal);if(signal.aborted)return;const report=await options.inspect!(image,signal);if(!active()||signal.aborted||attempt!==epoch)return;
   options.onDecision(report.decision);if(report.decision!=='allow'){result.hidden=true;selection.clear();status.textContent=report.decision==='block'?'Choose another photo. Intimate images and adult products cannot be used for a gift.':'We could not confidently approve this photo. Choose a different, clear photo of an everyday object or place.';return;}
   inspected=true;const detected=report.results.find(x=>x.id==='original')?.objectHint;hint=categories.some(x=>x[0]===detected)?detected!:'unknown';select.value=hint;result.hidden=false;selection.clear();presetFacts=undefined;presetRegion=undefined;presetStory=undefined;render();
   status.textContent=hint==='unknown'?'Photo checked locally. Choose a category to explore, or tell its own story.':`Photo checked locally. It may be a ${categories.find(x=>x[0]===hint)![1].toLowerCase()}. You can change the category.`;
  }catch(error){if(!active()||signal.aborted||attempt!==epoch)return;options.onDecision(undefined);status.textContent=error instanceof Error?error.message:'Photo checking is unavailable. Please try again.';}finally{if(active()&&attempt===epoch){button.disabled=false;button.textContent='Discover its story ↗';}}})();
 },{signal:events.signal});
 select.addEventListener('change',()=>{hint=select.value;selection.clear();presetFacts=undefined;presetRegion=undefined;presetStory=undefined;render();options.onChange();},{signal:events.signal});
 host.querySelector('[data-curio-use-seed]')!.addEventListener('click',()=>options.onStory(presetStory||seeds[hint]||seeds.unknown),{signal:events.signal});
 return {reset,preset(value){if(!active())return;reset();presetFacts=selectedCuriosities([...value.factIds]);presetRegion=value.regionId;presetStory=value.story;hint=value.objectHint||'landscape';select.value=hint;inspected=true;result.hidden=false;status.textContent='Artistic reference · these sourced facts describe the inspiration. Choose what you want to include.';render();},refreshRegion(){if(inspected){render();options.onChange();}},selectedIds:()=>[...selection],destroy(){dead=true;epoch++;request?.abort();events.abort();host.replaceChildren();}};
}
