import './quality-reference-capture.css';
import { BackSide, Mesh, MeshBasicMaterial, NoToneMapping, PerspectiveCamera, Scene, SphereGeometry, SRGBColorSpace, TextureLoader, Vector3, WebGLRenderer, type Texture } from 'three';

export interface QualityReferenceCaptureOptions { isCurrent(): boolean; onExit(): void }
export interface QualityReferenceCaptureHandle { destroy(): void }
const views = [{ id: 'front', label: 'Front', yaw: 0 }, { id: 'right', label: 'Right', yaw: 90 }, { id: 'back', label: 'Back', yaw: 180 }, { id: 'left', label: 'Left', yaw: 270 }] as const;
const sourceUrl = '/demo/v13/paris-panorama.png';
const size = 768, fieldOfView = 110, pitch = 0;

/** Four overlapping, perspective views of one existing panorama. No generation. */
export function mountQualityReferenceCapture(host: HTMLElement, options: QualityReferenceCaptureOptions): QualityReferenceCaptureHandle {
  const events = new AbortController(), downloads = new Set<string>(), timers = new Set<ReturnType<typeof setTimeout>>();
  let dead = false, ready = false, selected: typeof views[number] = views[0];
  let renderer: WebGLRenderer | undefined, texture: Texture | undefined;
  const current = () => !dead && options.isCurrent();
  host.innerHTML = `<main class="quality-reference-capture"><header><span>GiftPortals · Reference capture</span><button data-qrc-exit type="button">Back to comparison</button></header><div class="qrc-workspace"><div class="qrc-canvas" data-qrc-canvas></div><section class="qrc-panel"><span class="qrc-eyebrow">ONE PANORAMA · FOUR COHERENT VIEWS</span><h1>Around the same place.</h1><p>This renders perspective views from the existing Paris panorama. The virtual camera stays at the same position; only its direction changes.</p><nav aria-label="Panorama view">${views.map(view => `<button type="button" data-qrc-view="${view.id}" aria-pressed="${view.id === selected.id}">${view.label}<span>${view.yaw}°</span></button>`).join('')}</nav><dl><div><dt>Direction</dt><dd data-qrc-direction>Front · 0°</dd></div><div><dt>Image size</dt><dd>768 × 768</dd></div><div><dt>Field of view</dt><dd>110° · 20° overlap</dd></div><div><dt>Pitch</dt><dd>0°</dd></div><div><dt>Source</dt><dd>Existing Paris world panorama</dd></div></dl><p class="qrc-status" role="status" data-qrc-status>Opening the existing panorama…</p><button class="qrc-download" type="button" data-qrc-download disabled>Download this view ↓</button><small>No new AI image or environment is generated by this tool.</small></section></div></main>`;
  const frame = host.querySelector<HTMLElement>('[data-qrc-canvas]')!, status = host.querySelector<HTMLElement>('[data-qrc-status]')!;
  const download = host.querySelector<HTMLButtonElement>('[data-qrc-download]')!;
  const scene = new Scene(), camera = new PerspectiveCamera(fieldOfView, 1, .1, 30);
  const geometry = new SphereGeometry(10, 64, 48), material = new MeshBasicMaterial({ side: BackSide });
  const sphere = new Mesh(geometry, material); scene.add(sphere);
  function render() {
    if (!current() || !ready || !renderer) return;
    const radians = selected.yaw * Math.PI / 180;
    const elevation = pitch * Math.PI / 180; camera.lookAt(new Vector3(Math.sin(radians) * Math.cos(elevation), Math.sin(elevation), -Math.cos(radians) * Math.cos(elevation)));
    renderer.render(scene, camera);
    frame.setAttribute('data-quality-ready', 'true'); frame.setAttribute('data-quality-view', selected.id);
    host.querySelector<HTMLElement>('[data-qrc-direction]')!.textContent = `${selected.label} · ${selected.yaw}°`;
    host.querySelectorAll<HTMLButtonElement>('[data-qrc-view]').forEach(button => button.setAttribute('aria-pressed', String(button.getAttribute('data-qrc-view') === selected.id)));
    status.textContent = `${selected.label} view ready. This is a geometric view of the existing panorama.`;
  }
  host.addEventListener('click', event => {
    if (!current()) return;
    const target = event.target instanceof Element ? event.target.closest<HTMLButtonElement>('button') : null;
    if (!target || !host.contains(target)) return;
    if (target.hasAttribute('data-qrc-exit')) options.onExit();
    const view = views.find(view => view.id === target.getAttribute('data-qrc-view'));
    if (view) { selected = view; render(); }
    if (target.hasAttribute('data-qrc-download') && ready && renderer) {
      const viewId = selected.id;
      renderer.domElement.toBlob(blob => {
        if (!blob || !current()) return;
        const url = URL.createObjectURL(blob); downloads.add(url);
        const link = document.createElement('a'); link.href = url; link.download = `paris-${viewId}-768.png`; link.click();
        status.textContent = `${viewId[0].toUpperCase()}${viewId.slice(1)} view exported as PNG.`;
        const timer = setTimeout(() => { URL.revokeObjectURL(url); downloads.delete(url); timers.delete(timer); }, 30_000); timers.add(timer);
      }, 'image/png');
    }
  }, { signal: events.signal });
  try {
    renderer = new WebGLRenderer({ antialias: true, alpha: false, preserveDrawingBuffer: true });
    renderer.setPixelRatio(1); renderer.setSize(size, size, false); renderer.outputColorSpace = SRGBColorSpace; renderer.toneMapping = NoToneMapping;
    renderer.domElement.setAttribute('aria-label', 'Perspective view of the existing Paris panorama'); frame.append(renderer.domElement);
    new TextureLoader().load(sourceUrl, loaded => {
      if (!current()) { loaded.dispose(); return; }
      texture = loaded; texture.colorSpace = SRGBColorSpace; material.map = texture; material.needsUpdate = true;
      ready = true; download.disabled = false; render();
    }, undefined, () => { if (current()) status.textContent = 'The existing panorama could not be loaded. No view was exported.'; });
  } catch { status.textContent = '3D rendering is unavailable on this device. No view was exported.'; }
  return { destroy() { if (dead) return; dead = true; events.abort(); timers.forEach(clearTimeout); downloads.forEach(url => URL.revokeObjectURL(url)); texture?.dispose(); geometry.dispose(); material.dispose(); renderer?.dispose(); renderer?.forceContextLoss(); host.replaceChildren(); } };
}
